#!/usr/bin/env python3
"""
extract_data.py — extract the Compunet client's data section (HUNK 27) as a
linkable vasm assembly module, preserving all 406 relocations.

The data section holds ~400 Intuition structures (NewWindow, Gadget, Image,
IntuiText, menus) that are impractical to hand-author but trivial to reproduce
byte-for-byte. Its internal pointers are relocations:
  - 310 self-relative (data->data): emitted as `dc.l L_<off>` label references so
    vlink fixes them wherever the blob lands.
  - 93 code pointers (data->code): emitted as `dc.l <symbol>` referencing the
    reconstructed C functions (the control tables, command dispatch, etc.), so they
    bind to OUR code, not the original's layout.

Output: g_data_blob.asm (vasm mot syntax). The symbol `g_data` marks the base; the
UI code addresses individual structures as `g_data + 0xNNN` via accessors in a
generated header g_data_offsets.h.

This is the "keep data as extracted blob, reconstruct code" strategy: correctness of
the data is proven (byte-identical), while behaviour is readable C.
"""
import sys, importlib.util

BASE = 0x100000
ALIGN = 0x1000
BIN = '../../decrunched/Compunet'

spec = importlib.util.spec_from_file_location("flatten", "flatten.py")
fl = importlib.util.module_from_spec(spec); spec.loader.exec_module(fl)
hunks = fl.parse(open(BIN, 'rb').read())
addr = BASE
for h in hunks:
    h['addr'] = addr
    addr += (max(len(h['data']), h['alloc']*4) + ALIGN - 1) & ~(ALIGN - 1)

DATA = 27
h = hunks[DATA]
data = h['data']
dbase = h['addr']

# Map each code target address -> the reconstructed symbol that provides it.
# Control-table entries resolve to frame_control.c handlers; but since the tables
# THEMSELVES are reconstructed in C (g_ctrl_lo/g_ctrl_hi), we do NOT re-emit those
# slots from the blob — the C tables override them. For the remaining code pointers
# (command dispatch etc.) we bind to named externs the UI code defines.
CODE_SYM = {
    0x104000: "about_dialog",       # FUN_00104000 — the "About..." menu handler
                                    # (was wrongly bound to the no-op hook_render_entry)
    0x1122a6: "hook_save_config",
    0x1036d2: "hook_connect_menu",
    0x114000: "hook_serial_setup",
    0x102a0a: "hook_main_menu",
    0x10e000: "mail_prepare",
    0x10a384: "hook_link_entry",
    0x103704: "hook_connect_entry",
    0x10c428: "extend_life",
    0x10c510: "vote",
    0x10c582: "account",
    0x10956c: "hook_dir_0956c", 0x1095b0: "hook_dir_095b0",
    0x1095f6: "hook_dir_095f6", 0x10963c: "hook_dir_0963c",
    0x109682: "hook_dir_09682", 0x10984c: "hook_dir_0984c",
    0x109898: "hook_dir_09898",
    0x10a3d0: "hook_nav_0a3d0", 0x10a3f8: "hook_nav_0a3f8",
    0x10a43e: "hook_nav_0a43e", 0x10a484: "hook_nav_0a484",
    0x10a4ca: "hook_nav_0a4ca",
    0x1172f4: "hook_ed_172f4", 0x11733a: "hook_ed_1733a",
    0x117380: "hook_ed_17380", 0x1173c6: "hook_ed_173c6",
    0x11740c: "hook_ed_1740c", 0x117470: "hook_ed_17470",
}

reloc = {off: tgt for (off, tgt) in h['relocs']}
# classify
selfrel = {}   # off -> target data offset
codeptr = {}   # off -> code addr
for off, tgt in h['relocs']:
    kind = hunks[tgt]['kind']
    val = int.from_bytes(data[off:off+4], 'big')
    if kind == 'DATA' and tgt == DATA:
        selfrel[off] = val               # points within our blob
    else:
        codeptr[off] = hunks[tgt]['addr'] + val

# The two control tables live at data offsets 0x8a8 (32*4) and 0x928 (128*4); they
# are reconstructed in C, so skip emitting those bytes as pointers — leave as zero
# placeholders (C tables are used instead). Mark that range.
CTRL_LO = 0x8a8; CTRL_LO_END = CTRL_LO + 32*4
CTRL_HI = 0x928; CTRL_HI_END = CTRL_HI + 128*4

out = []
out.append("; g_data_blob.asm — extracted Compunet data section (HUNK 27), %d bytes." % len(data))
out.append("; Generated by extract_data.py. Relocations preserved: %d self, %d code." %
           (len(selfrel), len(codeptr)))
out.append("; DO NOT EDIT — regenerate from the original binary.")
out.append("        section data,data")
out.append("        xdef _g_data")
# externs for code pointers
for sym in sorted(set(CODE_SYM.values())):
    out.append("        xref _%s" % sym)
out.append("_g_data:")

i = 0
n = len(data)
# Precompute label set: every self-reloc target offset needs a label.
labels = set(selfrel.values())
def emit_bytes(lo, hi):
    j = lo
    while j < hi:
        chunk = data[j:min(j+16, hi)]
        out.append("        dc.b " + ",".join("$%02x" % b for b in chunk))
        j += len(chunk)

while i < n:
    if i in labels:
        out.append("L_%04x:" % i)
    if i in selfrel:
        out.append("        dc.l _g_data+$%04x    ; ->data" % selfrel[i]); i += 4; continue
    if i in codeptr:
        # control-table slots: emit 0 (C overrides); else bind to symbol
        if CTRL_LO <= i < CTRL_LO_END or CTRL_HI <= i < CTRL_HI_END:
            out.append("        dc.l 0                ; ctrl-table slot (C table used)"); i += 4; continue
        tgt = codeptr[i]
        sym = CODE_SYM.get(tgt)
        if sym:
            out.append("        dc.l _%s    ; ->code" % sym); i += 4; continue
        out.append("        dc.l _hook_%05x    ; ->code (unmapped)" % (tgt & 0xfffff)); i += 4; continue
    # find run until next special offset
    nxt = n
    for s in (labels, selfrel, codeptr):
        for o in s:
            if o > i and o < nxt: nxt = o
    # also stop at next label
    emit_bytes(i, nxt)
    i = nxt

# BSS tail (alloc bytes beyond data)
bss = h['alloc']*4 - len(data)
if bss > 0:
    out.append("        ds.b %d               ; BSS tail" % bss)

open("g_data_blob.asm", "w").write("\n".join(out) + "\n")
print("wrote g_data_blob.asm: %d data bytes, %d self-relocs, %d code-relocs, %d BSS" %
      (len(data), len(selfrel), len(codeptr), max(0,bss)))
# report unmapped code targets so we know what UI symbols to define
unmapped = sorted(set(t for o,t in codeptr.items()
                      if not (CTRL_LO<=o<CTRL_LO_END or CTRL_HI<=o<CTRL_HI_END)
                      and t not in CODE_SYM))
print("unmapped code targets (%d):" % len(unmapped), [hex(x) for x in unmapped])
