services:
  compunet-server:
    build: ./server
    ports:
      - "6400:6400"
      - "6502:6502"
    volumes:
      - ./server/cfg:/app/cfg
      - ./server/data:/app/data
    restart: unless-stopped
