; =================================================================
; COMPUNET TERMINAL v1.22 — Full ROM Source
; =================================================================
; Assembler: ca65 (cc65 suite)
; Original: Ariadne Software Ltd, September 1984
; Auto-generated by gen_source.py from original ROM binary
;
; This file assembles to a byte-identical copy of the original ROM.
; =================================================================

; --- KERNAL Routines ---
KERNAL_IOINIT   = $FF84
KERNAL_RAMTAS   = $FF87
KERNAL_RESTOR   = $FF8A
KERNAL_CINT     = $FF81
KERNAL_CHROUT   = $FFD2
KERNAL_CHRIN    = $FFCF
KERNAL_GETIN    = $FFE4
KERNAL_CLRCHN   = $FFCC
KERNAL_SETLFS   = $FFBA
KERNAL_SETNAM   = $FFBD
KERNAL_LOAD     = $FFD5
KERNAL_SAVE     = $FFD8
KERNAL_UDTIM    = $FFEA
KERNAL_STOP     = $FFE1

; --- BASIC ROM ---
BASIC_RUNC      = $E453
BASIC_MAIN      = $E3BF
BASIC_LINKPRG   = $E422
BASIC_READY     = $A474

; --- VIC-II Registers ---
VIC_BORDER      = $D020
VIC_BGCOL0      = $D021

; --- CIA Registers ---
CIA1_PRA        = $DC00
CIA1_PRB        = $DC01
CIA1_TALO       = $DC04
CIA1_TAHI       = $DC05
CIA1_ICR        = $DC0D

; --- ACIA (SwiftLink) Registers ---
ACIA_DATA       = $DE00
ACIA_STATUS     = $DE01
ACIA_CMD        = $DE02
ACIA_CTRL       = $DE03

; --- System Vectors ---
IRQ_VECTOR      = $0314
NMI_VECTOR      = $0318

; --- Compunet Workspace ($C100-$C2FF) ---
CMD_BUFFER      = $C100   ; Command/login buffer
PROTO_STATE     = $C200   ; Protocol connection state
PROTO_SEQ_TX    = $C20E   ; Transmit sequence number
PROTO_SEQ_RX    = $C20F   ; Expected receive sequence
PROTO_SLOT_SEQ  = $C228   ; Slot sequence numbers (4 slots)
PROTO_SLOT_FLAG = $C22C   ; Slot status flags (4 slots)
PROTO_SLOT_IDX  = $C209   ; Current slot index
PROTO_PKT_HDR   = $C203   ; Packet header buffer (6 bytes)
PROTO_FLAGS     = $8038   ; Protocol state flags

; --- NMI Ring Buffer ---
NMI_BUF         = $CE00   ; 256-byte ring buffer
NMI_BUF_TAIL    = $029B   ; Write pointer (NMI handler advances)
NMI_BUF_HEAD    = $029C   ; Read pointer (main code advances)

.segment "HEADER"

    .byte $60, $81, $5E, $FE, $C3, $C2, $CD, $38, $30, $7C, $80, $A4, $80, $00, $00, $00  ; $8000 `.^....80|......
    .byte $00, $80, $04, $01, $06, $00, $E0, $04, $E0, $00, $E0, $40, $30, $3A, $00, $00  ; $8010 ...........@0:..
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; $8020 ................
    .byte $00, $00, $53, $0D, $43, $00, $02, $A0, $00, $09, $08, $14, $08, $11, $07, $36  ; $8030 ..S.C..........6
    .byte $34, $31, $32, $03, $14, $3E, $1A, $00, $03, $24, $01, $FF, $FF, $2A, $43, $4F  ; $8040 412..>...$...*CO
    .byte $4E, $1D, $43, $20, $43, $4E, $45, $54, $0D, $33, $32, $32, $35, $30, $30, $2F  ; $8050 N.C CNET.322500/
    .byte $31, $30, $30, $0D, $41, $44, $50, $0D, $4E, $4F, $0D, $52, $55, $4E, $0D, $00  ; $8060 100.ADP.NO.RUN..
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $0D, $20, $43, $4F, $4D, $50  ; $8070 ........... COMP
    .byte $55, $4E, $45, $54, $20, $54, $45, $52, $4D, $49, $4E, $41, $4C, $20, $31, $2E  ; $8080 UNET TERMINAL 1.
    .byte $32, $32, $0D, $00, $20, $53, $45, $50, $54, $45, $4D, $42, $45, $52, $20, $31  ; $8090 22.. SEPTEMBER 1
    .byte $39, $38, $34, $20, $41, $52, $49, $41, $44, $4E, $45, $20, $53, $4F, $46, $54  ; $80A0 984 ARIADNE SOFT
    .byte $57, $41, $52, $45, $20, $4C, $54, $44, $2E, $0D, $0D, $00, $00, $00, $00, $00  ; $80B0 WARE LTD........
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; $80C0 ................
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; $80D0 ................
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; $80E0 ................
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00  ; $80F0 ................
    JMP MAIN_INIT
    JMP L8355
    JMP MODEM_CHECK
    JMP MODEM_REG_WRITE_WAIT
    JMP MODEM_REG_READ_STATUS
    JMP MODEM_INIT_DOWNLOAD
    JMP MODEM_SEND_CMD
    JMP PROTOCOL_RESET
    JMP PROTOCOL_CLEANUP
    JMP SETUP_INPUT_PARAMS
    JMP INPUT_LINE
    JMP L89D0
    JMP L89E2
    JMP DISK_LOAD
    JMP DISK_SAVE
    JMP SCREEN_DRAW
    JMP L849B
    JMP L8446
    JMP L8477
    JMP L8500
    JMP FILE_OPS
    JMP PRINT_STRING
    JMP CURSOR_HOME
    JMP PRINT_STATUS_MSG
    JMP L8FFB
    JMP CLEAR_STATUS
    JMP STATUS_LINE
    JMP PROTOCOL_STATE_INIT
    JMP MODEM_STATUS_CHECK
    JMP FILE_UPLOAD
    JMP FILE_DOWNLOAD
    JMP FRAME_STORE

; ============================================================
; COLD_START
; ============================================================

; --- COLD_START ---
; Initialize C64 hardware, BASIC, and install command extensions
COLD_START:
    JSR KERNAL_IOINIT                   ; KERNAL_IOINIT
    JSR KERNAL_RAMTAS                   ; KERNAL_RAMTAS
    JSR KERNAL_RESTOR                   ; KERNAL_RESTOR
    JSR KERNAL_CINT                     ; KERNAL_CINT
    CLI
    LDA #$01
    STA VIC_BGCOL0                      ; VIC_BGCOL0 = white
    JSR BASIC_RUNC                      ; BASIC_RUNC
    JSR BASIC_MAIN                      ; BASIC_MAIN
    JSR BASIC_LINKPRG                   ; BASIC_LINKPRG

; This redirects BASIC's command input to our parser at $81BC
    LDX #$04
L817D:
    LDA $81B7,X
    STA $E000,X
    DEX
    BPL L817D
    LDY #$00
    STY $1D
    LDA #$80
    STA $1E
L818E:
    LDA ($1D),Y
    STA ($1D),Y
    INY
    BNE L818E
    INC $1E
    LDA $1E
    CMP #$A0
    BNE L818E
    JSR L8335

; Print " COMPUNET TERMINAL 1.22" version string

; --- MAIN_INIT ---
; Print version string, install BASIC command parser, enter READY prompt
MAIN_INIT:
    LDX #$7A
    LDY #$80
    JSR PRINT_STRING                    ; PRINT_STRING
    LDX #$BC
    LDY #$81
    STX $0302
    STY $0303
    LDX #$FB
    TXS
    JMP BASIC_READY                     ; BASIC_READY
    .byte $00, $F6, $F1, $0E, $00  ; $81B7 .....

; ============================================================
; BASIC_CMD_PARSER - Intercepts BASIC input to handle custom commands
; Commands: EDITOR, CONNECT, CNLOAD, CNSAVE, HELP
; ============================================================
L81BC:
    JSR $A560
    STX $7A
    STY $7B
    JSR $0073
    TAX
    BEQ L81BC
    LDX #$FF
    STX $3A
    BCS L81D2
    JMP $A49C

; Compare input buffer against command table at $8249
L81D2:
    LDX $7A
    LDY #$00
    STY $1A
L81D8:
    LDA $0200,X
    SEC
    SBC $8249,Y
    BNE L81E5
    INX
    INY
    BNE L81D8
L81E5:
    CMP #$80
    BEQ L81EA
    CLC
L81EA:
    LDA $1A
    BCS L8200
    DEY
    LDX $7A
    INC $1A
    CMP #$05
    BEQ L8237
L81F7:
    INY
    LDA $8249,Y
    BPL L81F7
    INY
    BNE L81D8

; Command matched - save screen state and dispatch
L8200:
    LDX VIC_BORDER                      ; VIC_BORDER
    STX $C151                           ; workspace
    LDX VIC_BGCOL0                      ; VIC_BGCOL0
    STX $C152                           ; workspace
    LDX $0286
    STX $C153                           ; workspace
    LDX #$36
    STX $01
    JSR L823E

; Restore screen state after command returns
    LDA $C151                           ; workspace
    STA VIC_BORDER                      ; VIC_BORDER
    LDA $C152                           ; workspace
    STA VIC_BGCOL0                      ; VIC_BGCOL0
    LDA $C153                           ; workspace
    STA $0286
    LDX #$37
    STX $01
    LDA #$09
    JSR KERNAL_CHROUT                   ; KERNAL_CHROUT
    JMP BASIC_READY                     ; BASIC_READY
L8237:
    LDX #$FF
    LDY #$01
    JMP $A486

; Dispatch via address table at $8269 (RTS trick)
L823E:
    ASL
    TAY
    LDA $826A,Y
    PHA
    LDA $8269,Y
    PHA
    RTS
    .byte $45, $44, $49, $54, $4F, $D2, $43, $4F, $4E, $4E, $45, $43, $D4, $43, $4E, $4C  ; $8249 EDITO.CONNEC.CNL
    .byte $4F, $41, $C4, $43, $4E, $53, $41, $56, $C5, $48, $45, $4C, $D0, $4F, $46, $C6  ; $8259 OA.CNSAV.HEL.OF.
    .byte $4C, $83, $2F, $8D, $AB, $82, $A8, $82, $74, $82, $9D, $82  ; $8269 L./.....t...
    LDX #$7A
    LDY #$80
    JSR PRINT_STRING                    ; PRINT_STRING
    LDX #$94
    LDY #$80
    JSR PRINT_STRING                    ; PRINT_STRING
    LDX #$06
    LDY #$00
L8287:
    JSR L906A
L828A:
    LDA $8249,Y
    PHP
    AND #$7F
    JSR KERNAL_CHROUT                   ; KERNAL_CHROUT
    INY
    PLP
    BPL L828A
    JSR L906E
    DEX
    BNE L8287
    RTS
    LDX #$83
    LDY #$A4
    STX $0302
    STY $0303
    RTS
    SEC
    BCS L82AD
    CLC
L82AD:
    ROR $19
    JSR L92AD
    BCS L82C3
    LDA #$08
    PHA
    BIT $19
    BPL L82C6
    LDA #$07
    LDX #$2E
    LDY #$83
    BNE L82CC
L82C3:
    LDA #$01
    PHA
L82C6:
    LDA #$04
    LDX #$31
    LDY #$83
L82CC:
    JSR KERNAL_SETNAM                   ; KERNAL_SETNAM
    PLA
    TAX
    LDY #$01
    JSR KERNAL_SETLFS                   ; KERNAL_SETLFS
    LDX #$F0
    LDY #$9F
    STX $1D
    STY $1E
    BIT $19
    BPL L82F4
    LDA #$1D
    LDX $8036
    LDY $8037
    JSR KERNAL_SAVE                     ; KERNAL_SAVE
    JSR L935F
    BNE L8317
    BEQ L832B
L82F4:
    JSR L8335
    LDA #$00
    JSR KERNAL_LOAD                     ; KERNAL_LOAD
    BCC L8304
    JSR L935F
    JMP L830F
L8304:
    STX $8036
    STY $8037
    JSR L935F
    BEQ L832B
L830F:
    JSR L8335
    BIT $C156                           ; workspace
    BMI L832B
L8317:
    JSR L906E
    LDX #$53
    LDY #$93
    JSR PRINT_STRING                    ; PRINT_STRING
    LDX #$00
    LDY #$02
    JSR PRINT_STRING                    ; PRINT_STRING
    JSR L906E
L832B:
    JMP L92E0
    .byte $40, $30, $3A, $43, $4E, $45, $54  ; $832E @0:CNET
L8335:
    LDA #$00
    STA $9FF0
L833A:
    LDA #$30
    STA $A000
    STA $A001
    LDX #$02
    LDY #$A0
    STX $8036
    STY $8037
    RTS
    .byte $A9, $FF, $8D, $4B, $80, $8D, $4C, $80  ; $834D ...K..L.
L8355:
    JSR L89DC
    LDA $804B
    STA $1D
    LDA $804C
    STA $1E
    LDY #$00
    LDX #$01
L8366:
    ASL $1E
    ROL $1D
    BCC L8382
    CPX #$0E
    BNE L8377
    JSR L874B
    LDX #$0E
    BCS L8382
L8377:
    TXA
    STA $C175,Y
    LDA $83FD,X
    STA $C166,Y
    INY
L8382:
    INX
    CPX #$0F
    BNE L8366
    STY $C165                           ; workspace
    LDX #$AA
    LDY #$83
    JSR PROTOCOL_RESET                  ; PROTOCOL_RESET
    LDA #$01
    STA $8033
L8396:
    LDA #$08
    JSR KERNAL_CHROUT                   ; KERNAL_CHROUT
    LDX #$65
    LDY #$C1
    JSR PROTOCOL_CLEANUP                ; PROTOCOL_CLEANUP
    BCS L8396
    JSR L840C
    JMP L8396
    .byte $20, $48, $45, $4C, $50, $20, $20, $45, $44, $49, $54, $20, $20, $4C, $41, $53  ; $83AA  HELP  EDIT  LAS
    .byte $54, $20, $20, $4E, $45, $58, $54, $20, $20, $4E, $45, $57, $20, $20, $20, $43  ; $83BA T  NEXT  NEW   C
    .byte $4F, $50, $59, $20, $45, $52, $41, $53, $45, $20, $20, $47, $45, $54, $20, $20  ; $83CA OPY ERASE  GET  
    .byte $20, $50, $55, $54, $20, $20, $53, $54, $4F, $52, $45, $20, $50, $52, $49, $4E  ; $83DA  PUT  STORE PRIN
    .byte $54, $20, $20, $46, $52, $45, $45, $20, $20, $44, $4F, $53, $20, $20, $52, $45  ; $83EA T  FREE  DOS  RE
    .byte $54, $55, $52, $4E, $00, $06, $0C, $12, $18, $1E, $24, $2A, $30, $36, $3C, $42  ; $83FA TURN......$*06<B
    .byte $4E, $48  ; $840A NH
L840C:
    LDX $8033
    LDA $C174,X
    ASL
    TAX
    LDA $841C,X
    PHA
    LDA $841B,X
    PHA
    RTS
    .byte $38, $84, $5F, $87, $45, $84, $76, $84, $94, $84, $CA, $84, $D3, $84, $FF, $84  ; $841D 8._.E.v.........
    .byte $40, $85, $7F, $85, $DD, $85, $9B, $89, $5A, $87, $9D, $86  ; $842D @.......Z...
    LDX #$89
    LDY #$95                            ; FRAME_BUF_WRITE
    JSR L89E2
    JSR L8FFB
    JMP L89DC
L8446:
    LDX $8019
    LDY $801A
    CPX $8015
    BNE L8457
    CPY $8016
    BNE L8457
    RTS
L8457:
    STX $1D
    STY $1E
L845B:
    LDA $1D
    BNE L8461
    DEC $1E
L8461:
    DEC $1D
    JSR L8CB6
    CMP #$00
    BNE L845B
    LDA $1D
    STA $8019
    LDA $1E
    STA $801A
    JMP L89DC
L8477:
    JSR L8CAB
    JSR L8CC5
    LDX $1D
    LDY $1E
    CPX $8017
    BNE L848C
    CPY $8018
    BNE L848C
    RTS
L848C:
    STX $8019
    STY $801A
    JMP L89DC
L8495:
    JSR L849B
    JMP L89DC
L849B:
    CLC
    LDA $8017
    STA $8019
    STA $1D
    ADC #$04
    TAX
    LDA $8018
    STA $801A
    STA $1E
    ADC #$00
    BCC L84B9
    JSR L8C40
    JMP L849B
L84B9:
    STX $8017
    STA $8018
    JSR L8C05
    TXA
    JSR L8BC0
    LDA #$00
    JMP L8BC0
    JSR L849B
    JSR DISK_LOAD
    JMP L89DC
L84D4:
    LDX $8019
    LDY $801A
    JSR L8C70
    LDX $8019
    LDY $801A
    CPX $8017
    BNE L84ED
    CPY $8018
    BEQ L84F0
L84ED:
    JMP L89DC
L84F0:
    CPX $8015
    BNE L84FA
    CPY $8016
    BEQ L84FD                           ; KEYBOARD_SCAN
L84FA:
    JMP L8446
L84FD:
    JMP L8495
L8500:
    LDX #$3D
    LDY #$85                            ; CURSOR_HOME
    JSR CURSOR_HOME
    LDA #$52
    LDX #$53                            ; FILE_UPLOAD
    JSR FILE_UPLOAD
    BCS L8576
L8510:
    JSR L8495
    LDA #$8C                            ; workspace
    STA $C140
    LDA #$8A                            ; workspace
    STA $C141
    LDX #$08                            ; KERNAL_CHKIN
    JSR $FFC6
    BCS L8537
    JSR L89F0
    BCS L8537                           ; KERNAL_CLRCHN
    JSR KERNAL_CLRCHN
    JSR DISK_LOAD
    LDA $C15D
    BEQ L8510                           ; FRAME_STORE
    JMP FRAME_STORE
L8537:
    JSR $FFE7
    JMP L84D4
    .byte $47, $45, $54  ; $853D GET
    BRK
    LDX #$7C
    LDY #$85                            ; CURSOR_HOME
    JSR CURSOR_HOME
    LDA #$57
    LDX #$53                            ; FILE_UPLOAD
    JSR FILE_UPLOAD
    BCS L8576
    JSR L8CAB
    LDX #$08                            ; KERNAL_CHKOUT
    JSR $FFC9
    BCS L8576
    JSR L85D4
L855E:
    JSR KERNAL_CHROUT
    BCS L8576
    INC $1D
    BNE L8569
    INC $1E
L8569:
    JSR L8CB6
    CMP #$00
    BNE L855E                           ; KERNAL_CLRCHN
L8570:
    JSR KERNAL_CLRCHN
    JMP FRAME_STORE
L8576:
    JSR $FFE7
    JMP L89DC
    .byte $50, $55, $54  ; $857C PUT
    BRK
    LDX #$CE
    LDY #$85                            ; CURSOR_HOME
    JSR CURSOR_HOME
    LDA #$57
    LDX #$53                            ; FILE_UPLOAD
    JSR FILE_UPLOAD
    BCS L8576
    LDX $8015
    LDY $8016
    STX $1D
    STY $1E
    LDX #$08                            ; KERNAL_CHKOUT
    JSR $FFC9
    BCS L8576
    JSR L85D4
L85A4:
    JSR KERNAL_CHROUT
    BCS L8576
    INC $1D
    BNE L85AF
    INC $1E
L85AF:
    JSR L8CB6
    CMP #$00
    BNE L85A4
    LDX $1D
    CPX $8017
    BNE L85C4
    LDX $1E
    CPX $8018
    BEQ L8570
L85C4:
    JSR L85D4
    JSR KERNAL_CHROUT
    BCS L8576
    BCC L85A4
    .byte $53, $54, $4F, $52, $45, $00  ; $85CE STORE.
L85D4:
    LDA #$00
    BIT $C156
    BPL L85DD
    LDA #$01
L85DD:
    RTS
    .byte $AE, $19, $80, $AC, $1A, $80  ; $85DE ......

; --- SCREEN_DRAW ---
; Render frame/page to screen
SCREEN_DRAW:
    STX $1D
    STY $1E
    LDA #$81
    STA $C140
    LDA #$8A
    STA $C141
    JSR L8A7E
    JSR L8A7E
    JSR L8A7E
    LDA #$00
    STA $C15F
    JSR L8A4B                           ; workspace
    STA $C15E
    LDA #$04
    TAX                                 ; KERNAL_SETLFS
    LDY #$00
    JSR KERNAL_SETLFS
    LDA #$00
    JSR KERNAL_SETNAM                   ; KERNAL_OPEN
    JSR $FFC0
    LDX #$04
    JSR $FFC9
    BCS L8677
L861D:
    JSR KERNAL_GETIN
    CMP #$03
    BEQ L8674
    JSR L8A4B
    CMP #$00
    BEQ L8674
    CMP #$0D
    BNE L8637
    JSR KERNAL_CHROUT
    BCS L8677
    JMP L861D
L8637:
    PHA
    LDX #$14
L863A:
    JSR L906A
    BCS L8677
    DEX                                 ; workspace
    BNE L863A
    BIT $C15E
    BMI L864E
    LDA #$11
    JSR KERNAL_CHROUT
    BCS L8677
L864E:
    PLA
    BNE L8663
L8651:
    JSR L8A4B
    CMP #$00
    BEQ L8674
    CMP #$0D
    BNE L8663
    JSR KERNAL_CHROUT
    BCS L8677
    BCC L861D
L8663:
    LDX #$0F
L8665:
    CMP $8BF5,X
    BEQ L8651
    DEX                                 ; KERNAL_CHROUT
    BPL L8665
    JSR KERNAL_CHROUT
    BCS L8677
    BCC L8651
L8674:
    JSR L906E
L8677:
    PHP
    JSR KERNAL_CLRCHN
    LDA #$04
    JSR $FFC3
    PLP
    BCC L86A3
    LDX #$90
    LDY #$86
    JSR PRINT_STATUS_MSG                ; CLEAR_STATUS
    JSR CLEAR_STATUS                    ; PROTOCOL_STATE_INIT
    JMP PROTOCOL_STATE_INIT
    .byte $50, $52, $49, $4E, $54, $45, $52, $20, $45, $52, $52, $4F, $52  ; $8690 PRINTER ERROR
    BRK

; --- FILE_OPS ---
; File operations dispatcher
FILE_OPS:
    JSR L874B
    BCC L86A4
L86A3:
    RTS                                 ; VIC_BGCOL0
L86A4:
    LDA $8013
    STA VIC_BGCOL0
    LDA $8014
    STA $0286
    LDX #$2A                            ; PRINT_STRING
    LDY #$87
    JSR PRINT_STRING
    LDX $7A                             ; workspace
    LDY $7B
    STX $C161
    STY $C162
L86C1:
    LDA #$40
    JSR KERNAL_CHROUT
    LDX #$26
    LDA #$00                            ; SETUP_INPUT_PARAMS
    TAY
    CLC
    JSR SETUP_INPUT_PARAMS
    LDX #$00
    LDY #$02
    STX $7A
    STY $7B
    INX
    JSR INPUT_LINE
    BCC L86EA
    LDX $C161
    LDY $C162
    STX $7A
    STY $7B
    JMP L89DC
L86EA:
    JSR L906E
    LDA #$00
    LDY $1A
    STA $0201,Y
    LDX IRQ_VECTOR
    LDY $0315
    STX $C163
    STY $C164
    LDX #$31
    LDY #$EA
    SEI
    STX IRQ_VECTOR
    STY $0315
    CLI
    LDX #$37
    STX $01
    LDA #$40
    JSR $CD10
    LDX #$36                            ; workspace
    STX $01
    LDX $C163
    LDY $C164
    SEI
    STX IRQ_VECTOR
    STY $0315
    CLI
    JMP L86C1
    .byte $93, $0E, $92, $11, $C9, $4E, $50, $55, $54, $20, $C4, $CF, $D3, $20, $43, $4F  ; $872A .....NPUT ... CO
    .byte $4D, $4D, $41, $4E, $44, $53, $20, $4F, $52, $20, $D3, $D4, $CF, $D0, $0D, $0D  ; $873A MMANDS OR ......
    .byte $00  ; $874A .
L874B:
    LDX #$02
L874D:
    LDA $7C,X
    CMP $CCDE,X
    BNE L8759
    DEX
    BPL L874D
    CLC
    RTS
L8759:
    SEC
    RTS
    PLA                                 ; KERNAL_CHROUT
    PLA
    JMP L9062
    LDA #$09
    JSR KERNAL_CHROUT
    LDA #$02
    STA $0286
    LDX #$19
L876C:
    LDA $D9,X
    ORA #$80
    STA $D9,X
    DEX
    BPL L876C
    CLC
    ROR $C15B                           ; PRINT_STATUS_MSG
L8779:
    LDX #$9B
    LDY #$88
    JSR PRINT_STATUS_MSG
    JSR L9066
L8783:
    LDA #$00
    STA $D4
    STA $D8
    JSR L8C26
    LDA $D6
    CMP #$18
    BNE L8797
    LDA #$91
    JSR KERNAL_CHROUT                   ; workspace
L8797:
    LDY $D3
    LDA ($D1),Y
    STA $C157
    JSR $EA24
    LDA ($F3),Y
    BIT $C15B
    BPL L87AB
    LDA $0286
L87AB:
    STA $C158
    LDA #$FF
    STA $C159
    STA $C15A
L87B6:
    JSR KERNAL_GETIN
    BNE L87E5                           ; workspace
    INC $C159
    BNE L87B6
    INC $C15A                           ; workspace
    BNE L87B6
    LDA #$E0
    STA $C15A
    LDY $D3
    LDA ($D1),Y
    EOR #$80
    STA ($D1),Y
    LDX $0286
    TXA                                 ; workspace
    EOR ($F3),Y
    AND #$0F
    BNE L87DF
    LDX $C158
L87DF:
    TXA                                 ; workspace
    STA ($F3),Y
    JMP L87B6
L87E5:
    PHA
    LDA $C157                           ; workspace
    LDY $D3
    STA ($D1),Y
    LDA $C158
    STA ($F3),Y                         ; PROTOCOL_STATE_INIT
    PLA
    CMP #$03
    BNE L886A
    JSR PROTOCOL_STATE_INIT
    LDX $8019
    LDY $801A
    JSR L8C70
    LDX $8017
    LDY $8018
    JSR DISK_SAVE
    LDX $8017
    LDY $8018
    STX $1F
    STY $20
    LDA $1D
    BNE L881C
    DEC $1E
L881C:
    DEC $1D
    LDA $1D
    STA $8017
    LDA $1E
    STA $8018
    CPX $8019
    BNE L8832
    CPY $801A
    BEQ L8869
L8832:
    LDY #$00
L8834:
    LDX #$34
    SEI
    STX $01
    LDA ($1F),Y
    LDX #$36
    STX $01
    CLI
    STA ($1D),Y
    LDA $1D
    BNE L8848
    DEC $1E
L8848:
    DEC $1D
    LDA $1F
    BNE L8850
    DEC $20
L8850:
    DEC $1F
    LDX $1F
    CPX $8019
    BNE L8834
    LDX $20
    CPX $801A
    BNE L8834
    LDX $8019
    LDY $801A
    JSR DISK_SAVE
L8869:
    RTS
L886A:
    CMP #$83
    BNE L8871
    JMP L89DC
L8871:
    CMP #$85
    BCC L888F
    CMP #$8D
    BCC L88A8
    CMP #$93
    BNE L8883
    JSR KERNAL_CHROUT
    JMP L8779
L8883:
    CMP #$94
    BNE L888F
    LDA #$20
    LDY #$27
    STA ($D1),Y
    LDA #$94
L888F:
    CMP #$A0
    BNE L8895
    LDA #$20
L8895:
    JSR KERNAL_CHROUT
    JMP L8783
    .byte $53, $54, $4F, $50, $20, $54, $4F, $20, $45, $58, $49, $54, $00  ; $889B STOP TO EXIT.
L88A8:
    SEC
    SBC #$85
    ASL
    TAX
    JSR L88B3
    JMP L8783
L88B3:
    LDA $88BD,X
    PHA
    LDA $88BC,X
    PHA
    RTS
    .byte $BA, $88, $F0, $88, $DE, $88, $CB, $88, $BA, $88, $3D, $89, $E7, $88, $D1  ; $88BC ..........=....
    DEY
    INC VIC_BGCOL0
    JMP L88D5
    .byte $EE, $20, $D0  ; $88D2 . .
L88D5:
    JSR PROTOCOL_STATE_INIT
    LDX #$9B
    LDY #$88
    JMP PRINT_STATUS_MSG
    .byte $AD, $8A, $02, $49, $80, $8D, $8A, $02  ; $88DF ...I....
    RTS
    .byte $AD, $5B, $C1, $49, $80, $8D, $5B  ; $88E8 .[.I..[
    CMP ($60,X)
    LDX $D6
    BEQ L893D
    LDA $D1
    STA $1D
    SEC
    SBC #$28
    STA $D1
    STA $1F
    LDA $D2
    STA $1E
    SBC #$00
    STA $D2
    STA $20
    DEC $D6
L890C:
    JSR L8983
    LDY #$27
L8911:
    LDA ($1D),Y
    STA ($1F),Y
    LDA ($21),Y
    STA ($23),Y
    DEY
    BPL L8911
    INX
    CPX #$18
    BEQ L8934
    CLC
    LDA $1D
    STA $1F
    ADC #$28
    STA $1D
    LDA $1E
    STA $20
    BCC L890C
    INC $1E
    BCS L890C
L8934:
    LDA #$20
    LDY #$27
L8938:
    STA ($1D),Y
    DEY
    BPL L8938
L893D:
    RTS
    LDA #$98
    STA $1D
    LDA #$07
    STA $1E
    LDA #$70
    STA $1F
    LDA #$07
    STA $20
    LDX #$17
L8950:
    CPX $D6
    BNE L895E
    LDA #$20
    LDY #$27
L8958:
    STA ($1D),Y
    DEY
    BPL L8958
    RTS
L895E:
    JSR L8983
    LDY #$27
L8963:
    LDA ($1F),Y
    STA ($1D),Y
    LDA ($23),Y
    STA ($21),Y
    DEY
    BPL L8963
    LDA $1F
    STA $1D
    SEC
    SBC #$28
    STA $1F
    LDA $20
    STA $1E
    SBC #$00
    STA $20
    DEX
    JMP L8950
L8983:
    LDA $1D
    STA $21
    LDA $1F
    STA $23
    LDA $1E
    AND #$03
    ORA #$D8
    STA $22
    LDA $20
    AND #$03
    ORA #$D8
    STA $24
    RTS
    LDX #$CF
    LDY #$89
    JSR CURSOR_HOME
    SEC
    LDA #$00
    SBC $8017
    TAX
    LDA #$00
    SBC $8018
    LDY #$37
    STY $01
    JSR $BDCD
    LDY #$36                            ; PRINT_STRING
    STY $01
    LDX #$C4
    LDY #$89
    JSR PRINT_STRING
    JMP CLEAR_STATUS
    .byte $20, $43, $48, $41, $52, $53, $20, $46, $52, $45, $45  ; $89C4  CHARS FREE

; --- FRAME_BUF_READ ---
; Read from frame buffer
FRAME_BUF_READ:
    .byte $00  ; $89CF .
L89D0:
    LDA #$AD
    STA $C140
    LDA #$8A
    STA $C141
    BNE L89F0
L89DC:
    LDX $8019
    LDY $801A                           ; workspace
L89E2:
    STX $1D
    STY $1E                             ; workspace
    LDA #$81
    STA $C140
    LDA #$8A
    STA $C141
L89F0:
    LDA #$00
    STA $C15D
    JSR L8A7E
    BCS L8A3B
    STA $8035
    JSR L9050
    JSR L8A7E
    BCS L8A3B
    STA VIC_BORDER
    JSR PROTOCOL_STATE_INIT
    JSR L8A7E
    BCS L8A3B
    STA VIC_BGCOL0
    LDA #$00
    STA $C15F
L8A18:
    JSR L8A4B
    BCS L8A3B
    CMP #$00
    BEQ L8A37
    CMP #$0D
    BNE L8A31                           ; KERNAL_CHROUT
    JSR L8C26
    BCC L8A2F                           ; KERNAL_CHROUT
    LDA #$91
    JSR KERNAL_CHROUT
L8A2F:
    LDA #$0D
L8A31:
    JSR KERNAL_CHROUT
    JMP L8A18
L8A37:
    JSR L8C26
    CLC
L8A3B:
    LDA #$00
    STA $D4
    RTS
    LDY #$00
    STA ($D1),Y                         ; workspace
    INC $D1
    BNE L8A4A
    INC $D2
L8A4A:
    RTS                                 ; workspace
L8A4B:
    LDA $C15F
    BEQ L8A58
    DEC $C15F
    LDA $C160
    CLC
    RTS
L8A58:
    JSR L8A7E
    BCS L8A7D
    CMP #$06
    BNE L8A65
    LDA #$20
    BNE L8A6E
L8A65:
    CMP #$07                            ; workspace
    BNE L8A7C
    JSR L8A7E
    BCS L8A7D
L8A6E:
    STA $C160
    JSR L8A7E
    BCS L8A7D
    STA $C15F
    LDA $C160
L8A7C:
    CLC
L8A7D:
    RTS
L8A7E:
    JMP ($C140)
    JSR L8CB6
    INC $1D
    BNE L8A8A
    INC $1E
L8A8A:
    CLC
    RTS
    .byte $AE  ; $8A8C .
    EOR $F0C1,X                         ; KERNAL_CHKIN
    .byte $03, $A9, $00, $60  ; $8A90 ...`
    LDX #$08
    JSR $FFC6
    BCS L8AAC
    JSR KERNAL_CHRIN
    BCS L8AAC
    CMP #$01
    BNE L8AA6
    LDA #$00
L8AA6:
    LDX $90
    STX $C15D
    CLC
L8AAC:
    RTS
    BIT $C15D
    BPL L8AB6                           ; workspace
    LDA #$00
    CLC

; ============================================================
; DISK_LOAD
; ============================================================
    RTS
L8AB6:
    JSR L96CC
    ROR $C15D
    CLC
    RTS

; --- DISK_LOAD ---
; Load file from disk
DISK_LOAD:
    LDX $8019
    LDY $801A
    JSR L8C70                           ; DISK_SAVE
    LDX $8017
    LDY $8018
    JSR DISK_SAVE
    LDX $8017
    LDY $8018
    STX $8019
    STY $801A
    LDY $1E
    LDX $1D
    BNE L8AE3

; ============================================================
; DISK_SAVE
; ============================================================
    DEY
L8AE3:
    DEX
    STX $8017
    STY $8018
    RTS

; --- DISK_SAVE ---
; Save file to disk
DISK_SAVE:
    STX $1D
    STY $1E
    JSR L8C05
    STX $19
    LDA #$00
    STA $1A
    LDA #$FF
    STA $C158
    JSR L9066
L8B00:
    JSR $EA24
    LDA #$12
    STA $C15C
    LDY #$00
L8B0A:
    LDA ($D1),Y
    CMP #$20
    BNE L8B17
    INY
    CPY #$28
    BNE L8B0A
    BEQ L8B69
L8B17:
    CPY #$00
    BEQ L8B27
    STY $D3
    LDA #$20
    JSR L8B7D
    LDY $D3
    DEY
    STY $1A
L8B27:
    LDY $D3
    LDA ($D1),Y
    PHA                                 ; workspace
    CMP #$20
    BEQ L8B45
    LDA ($F3),Y                         ; workspace
    AND #$0F
    CMP $C158
    BEQ L8B43
    STA $C158
    TAY                                 ; workspace
    LDA $8BF5,Y
    JSR L8B7D
L8B43:
    PLA
    PHA
L8B45:
    EOR $C15C
    BPL L8B58
    LDA $C15C
    JSR L8B7D
    LDA $C15C                           ; MODEM_STATUS_CHECK
    EOR #$80
    STA $C15C
L8B58:
    PLA
    JSR MODEM_STATUS_CHECK
    JSR L8B7D
    LDY $D3
    CPY #$27
    BEQ L8B69
    INC $D3
    BNE L8B27
L8B69:
    JSR L906E
    JSR L8B7D
    LDA $D6
    CMP #$18
    BEQ L8B78
    JMP L8B00
L8B78:
    LDA #$00
    JMP L8BC0
L8B7D:
    CMP $19
    BNE L8B84
    INC $1A
    RTS
L8B84:
    LDX $19
    STA $19
    CMP #$0D
    BNE L8B95
    CPX #$20
    BNE L8B95
    BIT $C15C
    BPL L8BBB
L8B95:
    TXA
    LDX $1A
    CPX #$02
    BCS L8BA4
L8B9C:
    JSR L8BC0
    DEX
    BPL L8B9C
    BMI L8BBB
L8BA4:
    CMP #$20
    BNE L8BAC
    LDA #$06
    BNE L8BB3
L8BAC:
    TAX
    LDA #$07
    JSR L8BC0
    TXA
L8BB3:
    JSR L8BC0
    LDA $1A
    JSR L8BC0
L8BBB:
    LDA #$00
    STA $1A
    RTS
L8BC0:
    LDY #$00
    STA ($1D),Y
    INC $1D
    BEQ L8BC9
    RTS
L8BC9:
    INC $1E
    BEQ L8BCE
    RTS
L8BCE:
    PHA
    TXA
    PHA
    JSR L8C40
L8BD4:
    JSR L8CB6
    LDY #$00
    STA ($1F),Y
    INC $1F
    BNE L8BE1
    INC $20
L8BE1:
    INC $1D
    BNE L8BD4
    INC $1E
    BNE L8BD4
    LDA $1F
    STA $1D
    LDA $20
    STA $1E
    PLA
    TAX
    PLA
    RTS
    .byte $90, $05, $1C, $9F, $9C, $1E, $1F, $9E, $81, $95, $96, $97, $98, $99, $9A, $9B  ; $8BF5 ................
L8C05:
    LDA #$00
    JSR L8BC0
    LDA VIC_BORDER
    ORA #$F0
    JSR L8BC0
    LDA VIC_BGCOL0
    ORA #$F0
    JSR L8BC0
    LDX #$0E
    LDA $D018
    AND #$02
    BNE L8C25
    LDX #$8E
L8C25:
    RTS
L8C26:
    LDA $D3
    CMP #$28
    BEQ L8C2E
    CLC
    RTS
L8C2E:
    SEC
    JSR $FFF0
    LDY #$00
    LDA $D9,X
    ORA #$80
    STA $D9,X
    CLC
    JSR $FFF0
    SEC
    RTS
L8C40:
    LDX $8015
    LDY $8016
    JSR L8C70
    LDX $8019
    LDY $801A
    CPX $8015
    BNE L8C59
    CPY $8016
    BEQ L8C6F
L8C59:
    SEC
    TXA
    SBC $1D
    TAX
    TYA
    SBC $1E
    TAY
    CLC
    TXA
    ADC $1F
    STA $8019
    TYA
    ADC $20
    STA $801A
L8C6F:
    RTS
L8C70:
    STX $1D
    STX $1F
    STY $1E
    STY $20
    JSR L8CC5
L8C7B:
    JSR L8CB6
    LDY #$00
    STA ($1F),Y
    BNE L8C92
    LDA $1D
    CMP $8017
    BNE L8C92
    LDA $1E
    CMP $8018
    BEQ L8CA0
L8C92:
    INC $1D
    BNE L8C98
    INC $1E
L8C98:
    INC $1F
    BNE L8C7B
    INC $20
    BNE L8C7B
L8CA0:
    LDA $1F
    STA $8017
    LDA $20
    STA $8018
    RTS
L8CAB:
    LDA $8019
    STA $1D
    LDA $801A
    STA $1E
    RTS
L8CB6:
    LDY #$34
    SEI
    STY $01
    LDY #$00
    LDA ($1D),Y
    LDY #$36
    STY $01
    CLI
    RTS
L8CC5:
    LDY #$34
    SEI
    STY $01
    LDY #$00
L8CCC:
    INC $1D
    BNE L8CD2
    INC $1E
L8CD2:
    LDA ($1D),Y
    BNE L8CCC
    LDY #$36
    STY $01
    CLI
    RTS
    .byte $0E, $CD, $4F, $44, $45, $4D, $20, $46, $41, $55, $4C, $54, $0D, $00, $93, $0E  ; $8CDC ..ODEM FAULT....
    .byte $08, $11, $C9, $4E, $50, $55, $54, $20, $50, $48, $4F, $4E, $45, $20, $4E, $55  ; $8CEC ...NPUT PHONE NU
    .byte $4D, $42, $45, $52, $00, $20, $4F, $52, $20, $D2, $C5, $D4, $D5, $D2, $CE, $2E  ; $8CFC MBER. OR .......
    .byte $00, $0D, $11, $CE, $55, $4D, $42, $45, $52, $3F, $20, $20, $00, $11, $C4, $49  ; $8D0C ....UMBER?  ...I
    .byte $41, $4C, $4C, $49, $4E, $47, $20, $00, $50, $4C, $45, $41, $53, $45, $20, $57  ; $8D1C ALLING .PLEASE W
    .byte $41, $49, $54, $00  ; $8D2C AIT.

; --- MODEM_CHECK ---
; Verify modem present, initialize hardware
MODEM_CHECK:
    TSX
    STX $C154
    LDX #$03                            ; MODEM_REG_READ
    LDA #$20
    JSR MODEM_REG_WRITE
    JSR MODEM_REG_READ
    CMP #$20
    BNE L8D4B
L8D42:
    JSR MODEM_REG_READ
    BEQ L8D52
    CMP #$20
    BEQ L8D42
L8D4B:
    LDX #$DC
    LDY #$8C
    JMP PRINT_STRING
L8D52:
    JSR L9050
    LDA $8013
    STA VIC_BGCOL0
    LDA $8014
    STA $0286
    LDX #$EA
    LDY #$8C
    JSR PRINT_STRING                    ; PRINT_STRING
    LDY #$01
    LDA $9FF0
    BEQ L8D78
    LDX #$01                            ; SETUP_INPUT_PARAMS
    LDY #$8D
    JSR PRINT_STRING
    LDY #$00                            ; PRINT_STRING
L8D78:
    LDX #$10
    LDA #$2D
    SEC
    JSR SETUP_INPUT_PARAMS              ; INPUT_LINE
    LDX #$0D
    LDY #$8D
    JSR PRINT_STRING
    LDX #$00
    LDY #$02
    JSR INPUT_LINE
    BCC L8D91
    RTS
L8D91:
    JSR L906E
    LDX $1A
    BEQ L8DA4
    STX $9FF0
L8D9B:
    LDA $01FF,X
    STA $9FF0,X
    DEX
    BNE L8D9B
L8DA4:
    LDX #$19
    LDY #$8D
    JSR PRINT_STRING
    JSR PROTO_DISPATCH_TABLE
    JSR L96C6
    LDY #$03
    LDX #$08                            ; KERNAL_GETIN
L8DB5:
    LDA #$10
    JSR MODEM_REG_WRITE
L8DBA:
    JSR MODEM_REG_READ                  ; PROTO_DISPATCH_TABLE
    AND #$10
    BEQ L8DCB
    JSR KERNAL_GETIN
    CMP #$03
    BNE L8DBA
    JMP PROTO_DISPATCH_TABLE
L8DCB:
    DEY
    BNE L8DB5
    LDY #$00
L8DD0:
    LDA $9FF1,Y                         ; MODEM_REG_WRITE
    JSR KERNAL_CHROUT                   ; MODEM_REG_READ
    CMP #$2D
    BNE L8DEA
    LDX #$08
    LDA #$10
    JSR MODEM_REG_WRITE
L8DE1:
    JSR MODEM_REG_READ
    AND #$10                            ; MODEM_REG_WRITE
    BNE L8DE1
    BEQ L8DFC
L8DEA:
    AND #$0F
    BNE L8DF0
    LDA #$0A                            ; KERNAL_GETIN
L8DF0:
    ORA #$A0
    JSR MODEM_REG_WRITE
L8DF5:
    JSR MODEM_REG_READ
    AND #$20
    BNE L8DF5
L8DFC:
    JSR KERNAL_GETIN
    CMP #$03                            ; MODEM_REG_WRITE
    BEQ L8E1C
    INY
    CPY $9FF0
    BNE L8DD0
    LDX #$03
    LDA #$90
    JSR MODEM_REG_WRITE
    LDX #$08
    LDA #$40
    JSR MODEM_REG_WRITE
    JSR L96D5
    BCC L8E1F
L8E1C:
    JMP PROTO_DISPATCH_TABLE
L8E1F:
    LDX #$24
    LDY #$8D                            ; PROTO_DISPATCH_TABLE
    JSR PRINT_STATUS_MSG
    CLC
    ROR $C155
    JSR L96D2
    BCC L8E35
    JSR PROTO_DISPATCH_TABLE
    JMP L9062
L8E35:
    JSR L9050
L8E38:
    LDX #$07                            ; workspace
    LDY #$95
    JSR L89E2
    LDA #$02
    STA $0286
    LDA #$5A
    STA $C100
    LDX #$10
    LDY #$12
    CLC
    JSR $FFF0
    LDX #$08                            ; INPUT_LINE
    LDY #$01
    LDA #$00
    CLC
    JSR SETUP_INPUT_PARAMS
    LDX #$01
    LDY #$C1
    JSR INPUT_LINE
    BCS L8E38
    LDY $1A
    LDA #$20
L8E68:
    STA $C101,Y
    INY
    CPY #$08
    BCC L8E68                           ; KERNAL_CHROUT
    LDX #$12
    LDY #$0D
    CLC
    JSR $FFF0
    LDX #$00
L8E7A:
    LDA #$5F
    JSR KERNAL_CHROUT
    LDA #$9D
    JSR KERNAL_CHROUT
    JSR CLEAR_STATUS
    CMP #$0D
    BEQ L8EA3
    CPX #$06
    BEQ L8E7A
    STA $C109,X                         ; KERNAL_CHROUT
    CMP #$30
    BCC L8E7A
    CMP #$5B
    BCS L8E7A
    INX
    LDA #$2A
    JSR KERNAL_CHROUT
    JMP L8E7A
L8EA3:
    JSR L906A
    LDA #$20
L8EA8:
    STA $C109,X
    INX
    CPX #$06
    BCC L8EA8
    LDX #$37
    STX $01
    LDX #$09
L8EB6:
    LDA $8039,X
    STA $C10F,X
    DEX
    BPL L8EB6
    LDX #$36
    STX $01
    LDA $A000
    STA $C119
    LDA $A001
    STA $C11A
    LDX #$24                            ; MODEM_REG_WRITE_WAIT
    LDY #$8D
    JSR PRINT_STATUS_MSG
    LDA #$43
    STA $8034
    LDY #$1B
    JSR MODEM_REG_WRITE_WAIT
    JSR L96D2
    BCC L8EE8
    JMP L8E38
L8EE8:
    JSR L89D0
    SEC
    ROR $C155

; --- MODEM_INIT_DOWNLOAD ---
; Receive terminal software during LINKING phase
MODEM_INIT_DOWNLOAD:
    JSR L96CC
    JSR L96CC
    JSR L96CC
    STA $1F
    JSR L96CC
    STA $20
    BCS L8F38
    LDX #$3F
    LDY #$8F
    JSR PRINT_STATUS_MSG
    JSR L96CC
    STA $1D
    JSR L96CC
    STA $1E
    JSR L96CC
    JSR L96CC
    LDY #$00
L8F1A:
    JSR L96CC
    STA ($1D),Y
    BCS L8F29
    INC $1D
    BNE L8F1A
    INC $1E
    BNE L8F1A
L8F29:
    BIT $C155
    BPL L8F38
    LDX $1D
    LDY $1E
    STX $8036
    STY $8037
L8F38:
    CLC

; ============================================================
; MODEM_SEND_CMD
; ============================================================
    ROR $C155
    JMP ($001F)
    JMP $4E49
    .byte $4B, $49, $4E, $47, $00  ; $8F42 KING.

; --- MODEM_SEND_CMD ---
; Send command packet, handle disconnect states
MODEM_SEND_CMD:
    CPX #$00                            ; KERNAL_CLRCHN
    BEQ L8F7E
    STX $C150
    LDX $C154
    TXS
    JSR PROTO_DISPATCH_TABLE
    JSR KERNAL_CLRCHN
    JSR L8FF2
    LDA $C151
    STA VIC_BORDER
    LDY $C150
    LDX $8FAF,Y
    LDA $8FB4,Y
    TAY
    JSR PRINT_STATUS_MSG
    JSR CLEAR_STATUS
    LDA $C153
    STA $0286                           ; KERNAL_CLRCHN
    LDX #$DA
    LDY #$8F
    JMP PRINT_STRING
L8F7E:
    LDX $C154
    TXS                                 ; PRINT_STRING
    JSR KERNAL_CLRCHN
    LDA $8014
    STA $0286
    LDX #$F4
    LDY #$9C
    JSR PRINT_STRING
L8F92:
    LDA CIA1_PRB
    CMP CIA1_PRB
    BNE L8F92
    CMP #$FF
    BNE L8F92
    LDA #$00
    STA $C6
    BIT $8010
    BPL L8FAA
    JSR L96D8
L8FAA:
    JSR L8FF2
    JMP PROTO_DISPATCH_TABLE
    .byte $00, $BA, $BB, $D4, $D7, $C1, $8F, $8F, $8F, $8F, $20, $44, $49, $53, $43, $4F  ; $8FB0 .......... DISCO
    .byte $4E, $4E, $45, $43, $54, $45, $44, $20, $2D, $20, $42, $41, $44, $20, $4C, $49  ; $8FC0 NNECTED - BAD LI
    .byte $4E, $45, $3F, $00, $57, $52, $00, $52, $57, $00, $93, $0E, $43, $4F, $4E, $4E  ; $8FD0 NE?.WR.RW...CONN
    .byte $45, $43, $54, $20, $41, $47, $41, $49, $4E, $20, $50, $4C, $45, $41, $53, $45  ; $8FE0 ECT AGAIN PLEASE
    .byte $0D, $00  ; $8FF0 ..
L8FF2:
    BIT $C155
    BPL L8FFA
    JSR L833A
L8FFA:
    RTS                                 ; KERNAL_GETIN
L8FFB:
    LDX #$10
    LDY #$90
    JSR PRINT_STATUS_MSG

; --- CLEAR_STATUS ---
; Clear the status bar
CLEAR_STATUS:
    LDA #$00
    STA $C6
    STX $19
L9008:
    JSR KERNAL_GETIN
    BEQ L9008
    LDX $19
    RTS

; ============================================================
; ============================================================
    .byte $50, $52, $45, $53, $53, $20, $41, $4E, $59, $20, $4B, $45, $59, $00  ; $9010 PRESS ANY KEY.

; --- STATUS_LINE ---
; Display status line
STATUS_LINE:
    LDX #$01                            ; INPUT_LINE
    LDY #$01
    LDA #$00
    CLC
    JSR SETUP_INPUT_PARAMS
    LDX #$00
    LDY #$02
    JSR INPUT_LINE
    BCS L903E
    LDA $0200
    AND #$DF
    CMP #$59
    BEQ L904D
    CMP #$4E
    BEQ L904D                           ; STATUS_LINE
L903E:
    LDA #$9D
    JSR KERNAL_CHROUT
    CPY #$00
    BEQ STATUS_LINE                     ; PROTOCOL_STATE_INIT
    JSR KERNAL_CHROUT
    JMP STATUS_LINE
L904D:
    CMP #$59
    RTS
L9050:
    JSR L9062
    JSR PROTOCOL_STATE_INIT
    JSR L9076
    LDA #$00
    STA $D015
    LDA #$0E
    BNE L9078
L9062:
    LDA #$93
    BNE L9078
L9066:
    LDA #$13
    BNE L9078
L906A:
    LDA #$20                            ; KERNAL_CHROUT
    BNE L9078
L906E:
    LDA #$0D
    BNE L9078
L9072:
    LDA #$12
    BNE L9078
L9076:
    LDA #$92
L9078:
    JMP KERNAL_CHROUT

; --- PRINT_STATUS_MSG ---
; Print message on status bar
PRINT_STATUS_MSG:
    STX $1B
    STY $1C
    JSR L93B4
    LDA $0286

; ============================================================
; ============================================================
    PHA
    JSR L9097
    JSR L9076                           ; PROTOCOL_STATE_INIT
    PLA
    STA $0286
    JMP L93BF

; --- CURSOR_HOME ---
; Move cursor to home position
CURSOR_HOME:
    STX $1B
    STY $1C
L9097:
    JSR PROTOCOL_STATE_INIT
    JSR L90AF
    JSR L9072
    LDA VIC_BGCOL0
    AND #$0F
    TAX
    LDA $93A4,X

; ============================================================
; PRINT_STRING
; ============================================================
    STA $0286
    JMP L90BB
L90AF:
    LDX #$18
    LDY #$00
    CLC                                 ; KERNAL_CHROUT
    JMP $FFF0

; --- PRINT_STRING ---
; Print null-terminated string (X=lo, Y=hi)
PRINT_STRING:
    STX $1B
    STY $1C
L90BB:
    LDY #$00
L90BD:
    LDA ($1B),Y                         ; workspace
    BEQ L90C7
    JSR KERNAL_CHROUT
    INY
    BNE L90BD
L90C7:
    RTS

; --- SETUP_INPUT_PARAMS ---
; Configure input line parameters
SETUP_INPUT_PARAMS:
    STX $C143
    STY $C144
    STA $C146

; ============================================================
; INPUT_LINE
; ============================================================
    TAX
    LDA #$00
    ROR
    CPX #$00
    BEQ L90DB
    ORA #$40
L90DB:
    STA $C145
    RTS

; --- INPUT_LINE ---
; Read a line of user input
INPUT_LINE:
    STX $1D
    STY $1E                             ; KERNAL_CHROUT
    LDY #$00
    STY $1A
    STY $C6
L90E9:
    LDA #$00                            ; KERNAL_GETIN
    STA $D4
    LDA #$5F
    JSR KERNAL_CHROUT
    LDA #$9D
    JSR KERNAL_CHROUT
L90F7:
    JSR KERNAL_GETIN
    BEQ L90F7
    LDY $1A
    CMP #$03
    BNE L9107
    JSR L906A
    SEC
    RTS
L9107:
    CPY $C144
    BCC L9110
    CMP #$0D
    BEQ L916C
L9110:
    CPY #$00
    BEQ L9128                           ; KERNAL_CHROUT
    CMP #$14
    BNE L9128
    JSR L906A
    LDA #$9D
    JSR KERNAL_CHROUT
    JSR KERNAL_CHROUT
    DEC $1A
    JMP L90E9
L9128:
    CPY $C143
    BEQ L90F7
    BIT $C145
    BVC L9139
    CMP $C146
    BEQ L9162
    BNE L913B
L9139:
    BPL L9145
L913B:
    CMP #$30
    BCC L90F7
    CMP #$3A
    BCS L90F7
    BCC L9162
L9145:
    CMP #$22
    BEQ L90F7
    CMP #$20
    BCC L90F7
    CMP #$60
    BCC L9162
    TAX
    LDA $D018
    AND #$02
    BEQ L90F7
    TXA
    CMP #$A0
    BCC L90F7
    CMP #$E0
    BCS L90F7
L9162:
    JSR KERNAL_CHROUT
    STA ($1D),Y
    INC $1A
    JMP L90E9
L916C:
    JSR L906A
    CLC
    RTS

; --- FILE_UPLOAD ---
; Upload file to server (CNSAVE)
FILE_UPLOAD:
    STA $C147
    STX $8032
    LDX #$56
    LDY #$92
    JSR PRINT_STRING
    JSR L92AD
    LDY #$00
    BCS L9186
    INY
L9186:
    LDA #$00
    LDX #$10                            ; INPUT_LINE
    CLC
    JSR SETUP_INPUT_PARAMS
    LDA $D018                           ; VIC_MEMSETUP
    PHA
    LDX #$1E
    LDY #$80                            ; KERNAL_CHROUT
    JSR INPUT_LINE
    STY $19
    PLA
    STA $D018
    PHP
    LDA #$08
    JSR KERNAL_CHROUT
    PLP
    BCC L91AB
    JMP L924C
L91AB:
    BIT $C156
    BPL L91FA
    BMI L91BF

; --- FILE_DOWNLOAD ---
; Download file from server
FILE_DOWNLOAD:
    STA $C147
    STX $8032
    STY $19
    JSR L92AD
    BCC L91FA
L91BF:
    LDA $19
    LDX #$1E
    LDY #$80                            ; workspace
    JSR KERNAL_SETNAM
    LDA $8032
    CMP #$50
    BEQ L91F7
    LDY #$00                            ; KERNAL_SETLFS
    LDA $C147
    CMP #$57
    BNE L91D9                           ; CURSOR_HOME
    INY
L91D9:
    LDX #$01
    LDA #$08
    JSR KERNAL_SETLFS
    LDX #$6D
    LDY #$92
    JSR CURSOR_HOME
    JSR L9290
    JSR $FFC0
    JSR L92A2
    BCC L9250
    LDA #$08
    JSR $FFC3
L91F7:
    SEC
    BCS L9250
L91FA:
    LDY $19
    LDA $C147
    STA $8021,Y
    LDA $8032
    STA $801F,Y
    LDA #$2C
    STA $801E,Y
    STA $8020,Y                         ; KERNAL_SETNAM
    TYA
    CLC
    ADC #$06
    STA $C148                           ; KERNAL_SETLFS
    LDX #$1C                            ; KERNAL_OPEN
    LDY #$80
L921B:
    JSR KERNAL_SETNAM
    LDA #$08
    TAX
    TAY
    JSR KERNAL_SETLFS
    JSR $FFC0                           ; CURSOR_HOME
    JSR L92E8                           ; STATUS_LINE
    BCC L9250
    BPL L9250
    LDX #$64
    LDY #$92
    JSR CURSOR_HOME
    JSR STATUS_LINE                     ; workspace
    BNE L924C                           ; workspace
    JSR L92AD
    BCS L9250
    LDX #$1B
    LDY #$80
    INC $C148
    LDA $C148
    BNE L921B
L924C:
    JSR L92E0
    SEC
L9250:
    PHP
    JSR L9076
    PLP
    RTS
    .byte $09, $20, $46, $49, $4C, $45, $20, $4E, $41, $4D, $45, $3F, $20, $00, $52, $45  ; $9256 . FILE NAME? .RE
    .byte $50, $4C, $41, $43, $45, $3F, $20, $00, $C9, $0D, $D0, $04, $38, $66, $19, $60  ; $9266 PLACE? .....8f.`
    .byte $24, $19, $10, $13, $18, $66, $19, $48, $8A, $48, $98, $48  ; $9276 $....f.H.H.H
    JSR PROTOCOL_STATE_INIT
    JSR L90AF
    PLA
    TAY
    PLA
    TAX
    PLA
    JMP $F1CA
L9290:
    LDX #$6E
    LDY #$92
    STX $0326
    STY $0327
    CLC
    ROR $19
    LDA #$80
    JMP $FF90
L92A2:
    LDX #$CA
    LDY #$F1
    STX $0326
    STY $0327                           ; KERNAL_SETLFS
    RTS                                 ; KERNAL_OPEN
L92AD:
    LDA #$00
    JSR KERNAL_SETNAM
    LDA #$0F
    TAY
    LDX #$08                            ; workspace
    JSR KERNAL_SETLFS
    JSR $FFC0
    LDX #$0F

; ============================================================
; FRAME_STORE
; ============================================================
    JSR $FFC9
    PHP
    ROR $C156
    JSR KERNAL_CLRCHN
    PLP
    BCS L92E0
    RTS

; --- FRAME_STORE ---
; Store frame data
FRAME_STORE:
    JSR L9290
    LDA #$08
    JSR $FFC3
    BCC L92DA                           ; KERNAL_CLOSE
    JSR $FFE7
L92DA:
    JSR L92A2
    JSR L92E8
L92E0:
    PHP
    LDA #$0F
    JSR $FFC3
    PLP
    RTS
L92E8:
    JSR L935F
    PHP
    LDX #$00
    PLP
    BEQ L9306
    LDX #$A0
    CMP #$32
    BEQ L9306
    LDX #$80
    CMP #$36
    BNE L9306
    LDY $0201                           ; workspace
    CPY #$33
    BNE L9306
    LDX #$C0
L9306:
    STX $C149
    LDA #$20
    BIT $C149
    BPL L9339
    BVS L9339
    BNE L932B
    LDX #$00
L9316:
    LDA $0200,X
    INX
    CMP #$2C
    BNE L9316
L931E:
    LDA $0200,X
    INX                                 ; CURSOR_HOME
    CMP #$2C
    BNE L931E
    LDA #$00
    STA $01FF,X                         ; PRINT_STRING
L932B:
    LDX #$53                            ; workspace
    LDY #$93
    JSR CURSOR_HOME
    LDX #$00                            ; KERNAL_CLOSE
    LDY #$02
    JSR PRINT_STRING
L9339:
    ASL $C149
    BCC L9352
    LDA #$08
    JSR $FFC3                           ; workspace
    JSR L92E0
    LDA $C149
    BMI L9351
    JSR CLEAR_STATUS
    LDA $C149
L9351:
    SEC
L9352:
    RTS
    .byte $44, $49, $53, $4B, $20, $45, $52, $52, $4F, $52, $20, $00  ; $9353 DISK ERROR .
L935F:
    BIT $C156                           ; KERNAL_GETIN
    BPL L9367
    LDA #$00
    RTS
L9367:
    LDX #$0F
    JSR $FFC6
    LDX #$00
L936E:
    JSR KERNAL_GETIN
    CMP #$0D
    BEQ L937B                           ; KERNAL_CLRCHN
    STA $0200,X
    INX
    BNE L936E
L937B:
    LDA #$00
    STA $0200,X
    STA $90
    JSR KERNAL_CLRCHN
    LDA $0200
    CMP #$30
    RTS

; --- PROTOCOL_STATE_INIT ---
; Initialize protocol state variables
PROTOCOL_STATE_INIT:
    LDA VIC_BGCOL0
    AND #$0F
    TAX
    LDA $93A4,X
    TAX
    LDY #$27
L9397:
    LDA #$A0
    STA $07C0,Y
    TXA
    STA $DBC0,Y
    DEY
    BPL L9397
    RTS
    .byte $01, $00, $01, $00, $01, $01, $01, $00, $00, $01, $00, $01, $01, $00, $01, $00  ; $93A4 ................
L93B4:
    SEC                                 ; workspace
    JSR $FFF0
    STX $C14A
    STY $C14B
    RTS
L93BF:
    CLC
    LDX $C14A
    LDY $C14B
    JMP $FFF0

; --- PROTOCOL_RESET ---
; Reset protocol to idle state
PROTOCOL_RESET:
    STX $C14E
    STY $C14F
    RTS

; --- PROTOCOL_CLEANUP ---
; Clean up protocol resources
PROTOCOL_CLEANUP:
    STX $1D
    STY $1E
    LDX $C14E
    LDY $C14F
    STX $1F
    STY $20
    LDY #$00
    LDA ($1D),Y
    STA $C14C
L93E5:
    LDX #$00
    JSR L9436
    JSR CLEAR_STATUS
    CMP #$1D
    BNE L940E
    LDX #$01
L93F3:
    JSR L9436
    JSR L949B
    INX
    CPX #$06
    BNE L93F3
    LDY $8033
    CPY $C14C
    BNE L9408
    LDY #$00
L9408:
    INY
    STY $8033                           ; workspace
    BNE L93E5
L940E:
    CMP #$9D
    BNE L942B
    LDY $8033
    DEY
    BNE L941B
    LDY $C14C
L941B:
    STY $8033
    LDX #$05
L9420:
    JSR L9436
    JSR L949B
    DEX
    BNE L9420
    BEQ L93E5
L942B:
    CMP #$0D                            ; VIC_BGCOL0
    BNE L9434
    LDA $8033
    CLC
    RTS
L9434:
    SEC                                 ; workspace
    RTS
L9436:
    TXA
    PHA
    STX $1A
    LDA VIC_BGCOL0
    AND #$0F
    TAX
    LDA $93A4,X
    STA $C142
    LDA $8033
    SEC
    SBC #$03
    BEQ L9450
    BCS L9456
L9450:
    CLC
    ADC $C14C
    BEQ L9450
L9456:
    STA $19
    LDX #$00
L945A:
    LDY $19
    LDA ($1D),Y
    CLC
    ADC $1A
    TAY
    LDA ($1F),Y
    AND #$3F                            ; workspace
    CPX #$12
    BCC L946E
    CPX #$18
    BCC L9470
L946E:
    ORA #$80
L9470:
    STA $07C0,X
    LDA $C142
    STA $DBC0,X
    INX
    CPX #$28
    BEQ L9498
    INC $1A
    LDA $1A
    CMP #$06
    BNE L945A
    LDA #$00
    STA $1A
    LDY $19
    CPY $C14C                           ; VIC_CTRL1
    BNE L9493
    LDY #$00
L9493:
    INY
    STY $19
    BNE L945A
L9498:
    PLA

; ============================================================
; MODEM_STATUS_CHECK
; ============================================================
    TAX
    RTS
L949B:
    LDA $D011
    ASL
    BCS L949B
L94A1:
    LDA $D011
    ASL
    BCC L94A1
    RTS

; --- MODEM_STATUS_CHECK ---
; Check modem status register
MODEM_STATUS_CHECK:
    AND #$7F
    CMP #$20
    BCS L94B2
    ORA #$40
    BNE L94C0

; ============================================================
; MODEM_REG_WRITE_WAIT
; ============================================================
L94B2:
    CMP #$40                            ; workspace
    BCC L94C0
    CMP #$60
    BCS L94BE
    ORA #$80
    BNE L94C0
L94BE:
    EOR #$C0
L94C0:
    RTS

; --- MODEM_REG_WRITE_WAIT ---
; Send bytes from $C100 buffer via protocol engine
MODEM_REG_WRITE_WAIT:
    STY $C14D
    LDY #$00

; ============================================================
; MODEM_REG_READ_STATUS
; ============================================================
L94C6:
    LDA $C100,Y
    INY
    CPY $C14D
    PHP
    JSR L96C9
    PLP
    BCC L94C6
    RTS

; ============================================================
; MODEM_WAIT_READY
; ============================================================

; --- MODEM_REG_READ_STATUS ---
; Read modem status into $C100 buffer
MODEM_REG_READ_STATUS:
    LDY #$00
L94D7:
    JSR L96CC
    STA $C100,Y
    INY
    BCC L94D7
    LDA $8034
    RTS                                 ; MODEM_REG_SELECT

; --- MODEM_WAIT_READY ---
; Wait for modem TX ready, then send byte
MODEM_WAIT_READY:
    PHA
    LDX #$00
L94E7:
    JSR MODEM_REG_READ
    TAX

; ============================================================
; MODEM_REG_READ
; ============================================================
    BPL L94E7
    PLA                                 ; MODEM_REG_SELECT
    LDX #$04

; --- MODEM_REG_WRITE ---
; Write value to modem register (X=reg, A=value)
MODEM_REG_WRITE:
    PHP                                 ; MODEM_DATA
    SEI
    STX ACIA_DATA
    STA ACIA_STATUS
    PLP
    RTS

; --- MODEM_REG_READ ---
; Read modem register (X=reg, returns A=value)
MODEM_REG_READ:
    PHP
    SEI
    STX ACIA_DATA
    LDA ACIA_STATUS
    LDA ACIA_STATUS
    PLP
    RTS
    .byte $00, $F4, $FF, $8E, $07, $0D, $0C, $20, $20, $90, $B0, $07, $C0, $21, $AE, $9B  ; $9507 .......  ....!..
    .byte $0D, $20, $20, $90, $DD, $43, $4F, $4D, $50, $55, $4E, $45, $54, $20, $53, $59  ; $9517 .  ..COMPUNET SY
    .byte $53, $54, $45, $4D, $20, $4C, $4F, $47, $4F, $4E, $2E, $06, $0B, $DD, $9B, $0D  ; $9527 STEM LOGON......
    .byte $20, $20, $90, $DD, $06, $21, $DD, $9B, $0D, $20, $20, $90, $DD, $1F, $45, $4E  ; $9537   ...!...  ...EN
    .byte $54, $45, $52, $20, $55, $53, $45, $52, $20, $49, $44, $3A, $06, $13, $90, $DD  ; $9547 TER USER ID:....
    .byte $9B, $0D, $20, $20, $90, $DD, $06, $21, $DD, $9B, $0D, $20, $20, $90, $DD, $1F  ; $9557 ..  ...!...  ...
    .byte $50, $41, $53, $53, $57, $4F, $52, $44, $3A, $06, $18, $90, $DD, $9B, $0D, $20  ; $9567 PASSWORD:...... 
    .byte $20, $90, $DD, $06, $21, $DD, $9B, $0D, $20, $20, $90, $AD, $07, $C0, $21, $BD  ; $9577  ...!...  ....!.
    .byte $9B, $0D, $00, $F6, $FC, $0E, $0D, $06, $02, $1F, $C5, $44, $49, $54, $20, $CB  ; $9587 ...........DIT .
    .byte $45, $59, $53, $07, $0D, $03, $06, $02, $D3, $D4, $CF, $D0, $20, $CB, $C5, $D9  ; $9597 EYS......... ...
    .byte $06, $07, $46, $33, $2F, $34, $0D, $06, $02, $95, $53, $54, $4F, $50, $20, $45  ; $95A7 ..F3/4....STOP E
    .byte $44, $49, $54, $2C, $06, $05, $C4, $45, $4C, $45, $54, $45, $2F, $C9, $4E, $53  ; $95B7 DIT,...ELETE/.NS
    .byte $45, $52, $54, $0D, $06, $02, $53, $54, $4F, $52, $45, $20, $46, $52, $41, $4D  ; $95C7 ERT...STORE FRAM
    .byte $45, $06, $04, $4C, $49, $4E, $45, $20, $41, $42, $4F, $56, $45, $20, $43, $55  ; $95D7 E..LINE ABOVE CU
    .byte $52, $53, $4F, $52, $0D, $0D, $06, $02, $1F, $D2, $D5, $CE, $20, $CB, $C5, $D9  ; $95E7 RSOR........ ...
    .byte $06, $08, $46, $35, $0D, $06, $02, $95, $52, $45, $53, $54, $4F, $52, $45, $06  ; $95F7 ..F5....RESTORE.
    .byte $08, $CF, $4E, $2F, $CF, $46, $46, $20, $41, $55, $54, $4F, $2D, $52, $45, $50  ; $9607 ..N/.FF AUTO-REP
    .byte $45, $41, $54, $0D, $06, $02, $4F, $52, $49, $47, $49, $4E, $41, $4C, $0D, $06  ; $9617 EAT...ORIGINAL..
    .byte $12, $1F, $46, $36, $0D, $06, $02, $D3, $C8, $C9, $C6, $D4, $2D, $C3, $3D, $06  ; $9627 ..F6........-.=.
    .byte $07, $95, $CF, $4E, $2F, $CF, $46, $46, $20, $43, $4F, $4C, $4F, $55, $52, $0D  ; $9637 ...N/.FF COLOUR.
    .byte $06, $02, $43, $48, $41, $4E, $47, $45, $20, $43, $41, $53, $45, $06, $04, $4F  ; $9647 ..CHANGE CASE..O
    .byte $56, $45, $52, $57, $52, $49, $54, $45, $0D, $0D, $06, $12, $1F, $46, $37, $2F  ; $9657 VERWRITE.....F7/
    .byte $38, $0D, $06, $12, $95, $D3, $43, $52, $45, $45, $4E, $2F, $C2, $4F, $52, $44  ; $9667 8.....CREEN/.ORD
    .byte $45, $52, $0D, $06, $12, $43, $4F, $4C, $4F, $55, $52, $20, $43, $48, $41, $4E  ; $9677 ER...COLOUR CHAN
    .byte $47, $45, $07, $0D, $02, $06, $02, $1F, $D3, $45, $45, $20, $C8, $CF, $D7, $20  ; $9687 GE.......EE ... 
    .byte $D4, $CF, $20, $C5, $C4, $C9, $D4, $0D, $06, $02, $46, $4F, $52, $20, $46, $55  ; $9697 .. .......FOR FU
    .byte $4C, $4C, $45, $52, $20, $44, $45, $54, $41, $49, $4C, $53, $00, $00, $00, $00  ; $96A7 LLER DETAILS....
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00  ; $96B7 .........

; --- PROTO_DISPATCH_TABLE ---
; Protocol function dispatch (9 x JMP)
PROTO_DISPATCH_TABLE:
    JMP PROTO_SEND_PACKET               ; PROTO_ERROR_RECOVERY
    JMP PROTO_RECV_PACKET               ; PROTO_FLOW_CONTROL
L96C6:
    JMP PROTO_INIT_REGS                 ; PROTO_CONNECT
L96C9:
    JMP PROTO_RECV_FRAME

; ============================================================
; PROTO_INIT_REGS
; ============================================================
L96CC:
    JMP PROTO_PROCESS_CMD
    JMP PROTO_ERROR_RECOVERY
L96D2:
    JMP PROTO_FLOW_CONTROL
L96D5:
    JMP PROTO_CONNECT
L96D8:
    JMP $C800

; --- PROTO_INIT_REGS ---
; Initialize modem registers for protocol mode
PROTO_INIT_REGS:
    LDX #$02
    LDA #$40
    JSR MODEM_REG_WRITE
    LDX #$06
    LDA #$05                            ; workspace
    JMP MODEM_REG_WRITE

; --- PROTO_START_SESSION ---
; Start protocol session (set connected state)
PROTO_START_SESSION:
    BIT $8038
    BVC L96F3
    LDX #$04
    JMP MODEM_SEND_CMD
L96F3:
    LDA $C20E
    STA $C210
    STA $C211
    LDA #$80
    STA $8038
    LDX $8043
    LDA #$63
    LDY #$9C
    BNE L971F

; --- PROTO_DISCONNECT ---
; Handle disconnect / check connection state
PROTO_DISCONNECT:
    BIT $8038
    BPL L9714
    LDX #$05
    JMP MODEM_SEND_CMD
L9714:
    LDA #$40
    STA $8038
    LDX #$03
    LDA #$5A
    LDY #$9C
L971F:
    STX $C20A
    PHA
    LDA $9B03,X
    STA $23
    LDA $9B07,X
    STA $24
    PLA                                 ; workspace
    JSR L9C3D
    LDX $8046
    STX CIA1_TAHI                       ; workspace
    JSR L9E3C                           ; workspace
    LDA #$00                            ; workspace
    STA $C209
    STA $A2
    STA $A1
    STA $C218
    STA $C219
    STA $C224
    LDX #$0B
L974E:
    STA $C228,X
    DEX
    BPL L974E
    LDA #$34
    STA $21
    LDA #$C2
    STA $22
    LDA #$03
    STA $C20B
    RTS
L9762:
    LDY #$01
    LDA ($21),Y
    ORA #$40                            ; workspace
    STA ($21),Y
    LDA $C20B
    CLC
    ADC #$02
    DEY
    STA ($21),Y
    LDY #$00
    STY $C21D
    STY $C21E
L977B:
    LDA ($21),Y
    JSR L9B10
    INY                                 ; workspace
    CPY $C20B
    BNE L977B
    JSR L9B0B
    LDA $C21D
    STA ($21),Y
    INY
    LDA $C21E
    STA ($21),Y
    LDX $C209
    LDA #$80
    STA $C22C,X
L979C:
    JSR L98F5
    LDX $8043
L97A2:
    LDA $C22C,X
    BMI L979C
    DEX
    BPL L97A2
    JMP L9C2D

; --- PROTO_RECV_FRAME ---
; Send one byte and process receive (called per byte)
PROTO_RECV_FRAME:
    STA $19
    PHA
    TXA
    PHA                                 ; workspace
    TYA
    PHA
    PHP
    LDA $19
    PHA
    BIT $8038
    BMI L97C0
    JSR PROTO_START_SESSION
L97C0:
    LDX $C209
    LDA $C22C,X
    BPL L97EA
    CPX $8043
    BNE L97CF
    LDX #$FF
L97CF:
    INX
    STX $C209                           ; workspace
    LDA $9B03,X
    STA $21
    LDA $9B07,X
    STA $22                             ; workspace
    LDA #$03
    STA $C20B
    LDA $C228,X
    BEQ L97EA
    JSR L98F5                           ; workspace
L97EA:
    LDA $C20B
    CMP #$03
    BNE L9824
    LDY #$00
    STY $C21D
    STY $C21E
    LDA $8045
    STA ($21),Y                         ; workspace
    JSR L9B10
    INY
    LDA $8034
    STA ($21),Y
    JSR L9B10
    INY
    LDA $C20E
    LDX $C209
    STA $C228,X
    TAX
    INX                                 ; workspace
    CPX #$60
    BNE L981C
    LDX #$20
L981C:
    STX $C20E
    STA ($21),Y                         ; workspace
    JSR L9B10
L9824:
    LDY $C20B
    PLA
    STA ($21),Y
    JSR L9B10
    INY
    STY $C20B
    INY
    INY
    CPY $8045
    BNE L9851
    JSR L9B0B
    LDA $C21D
    LDY $C20B
    STA ($21),Y
    INY
    LDA $C21E
    STA ($21),Y
    LDX $C209
    LDA #$80
    STA $C22C,X
L9851:
    PLP
    BCC L985C
    JSR L9762
    LDA #$00
    STA $8038                           ; workspace
L985C:
    PLA
    TAY
    PLA                                 ; workspace
    TAX
    PLA
    RTS
L9862:
    LDX $8043
L9865:
    LDA $C228,X
    CMP $C211                           ; workspace
    BNE L987D
    LDY $C211
    INY
    CPY #$60                            ; workspace
    BNE L9877
    LDY #$20
L9877:
    STY $C211
    JMP L988B
L987D:
    DEX
    BPL L9865
    LDX $C20A
    CPX $8043
    BNE L988A
    LDX #$FF
L988A:
    INX
L988B:
    STX $C20A
    LDA $C22C,X                         ; workspace
    BPL L98F5                           ; workspace
    LDA $C228,X
    CMP $C220
    BNE L98B5
    LDA #$00
    STA $C221
    STA $C222
    LDA $804A
    BEQ L98B2                           ; workspace
L98A8:
    LDY $C22C,X
    BPL L98F5
    CMP $C222
    BNE L98A8
L98B2:
    LDA $C228,X
L98B5:
    STA $C220
    LDX #$19
    LDY $8034
    JSR L9BA4
    LDX $C20A
    LDA $9B03,X                         ; workspace
    STA $23
    LDA $9B07,X                         ; workspace
    STA $24
    JSR L991E
    LDY #$00                            ; workspace
    STY $C20C
    LDA ($23),Y
    STA $C20D
L98DA:
    LDA ($23),Y
    JSR L9926
    LDX $C20A
    LDA $C22C,X
    BPL L98F2
    INC $C20C
    LDY $C20C
    CPY $C20D
    BNE L98DA
L98F2:
    JSR L9922
L98F5:
    LDX $8043
L98F8:
    LDA $C228,X
    CMP $C210
    BEQ L9903
    DEX
    BPL L98F8                           ; workspace
L9903:
    LDA $C22C,X
    BPL L990B
    JMP L9862
L990B:
    LDA #$00                            ; workspace
    STA $C228,X
    LDX $C210
    INX
    CPX #$60
    BNE L991A
    LDX #$20
L991A:
    STX $C210
    RTS
L991E:
    LDA #$01
    BNE L9937
L9922:
    LDA #$02
    BNE L9937                           ; MODEM_WAIT_READY
L9926:
    CMP #$00
    BEQ L9937                           ; MODEM_WAIT_READY
    CMP #$04
    BCS L9937
    ADC #$20
    PHA
    LDA #$03
    JSR MODEM_WAIT_READY
    PLA
L9937:
    JMP MODEM_WAIT_READY

; --- PROTO_ERROR_RECOVERY ---
; Handle protocol errors, check for retransmit
PROTO_ERROR_RECOVERY:
    PHA
    TXA
    PHA
    TYA
    PHA
    BIT $8038
    BVS L9947
    JSR PROTO_DISCONNECT
L9947:
    BIT $C224                           ; workspace
    BMI L9964
    LDX #$03
L994E:
    LDA $C22C,X
    BPL L995B
    LDA $C228,X
    CMP $C20F
    BEQ L9964
L995B:
    DEX

; ============================================================
; PROTO_PROCESS_CMD
; ============================================================
    BPL L994E
    JSR L9A06
    SEC
    BCS L9965
L9964:
    CLC
L9965:
    PLA                                 ; PROTO_DISCONNECT
    TAY
    PLA
    TAX                                 ; workspace
    PLA
    RTS

; --- PROTO_PROCESS_CMD ---
; Process received command — delivers one byte to caller
PROTO_PROCESS_CMD:
    TXA
    PHA
    TYA
    PHA
    BIT $8038
    BVS L9977
    JSR PROTO_DISCONNECT                ; workspace
L9977:
    LDX $C209                           ; workspace
    LDA $C22C,X
    BMI L9986                           ; workspace
    JSR L9A17
    SEC
    ROR $C224
L9986:
    LDY $C20B
    LDA ($21),Y
    INY                                 ; workspace
    STY $C20B
    CPY $C217
    BEQ L9997
    CLC                                 ; workspace
    BCC L99E7
L9997:
    PHA                                 ; workspace
    LDA #$00
    LDX $C209
    STA $C228,X
    STA $C22C,X
    STA $C224
    BIT $C216
    CLC
    BPL L99E6
L99AC:
    LDA #$00
    STA $A2
    STA $A1
L99B2:
    LDA $A2
    CMP $8047
    BCS L99DD
    LDX #$03
L99BB:
    LDA $C22C,X
    BMI L99C5
    DEX
    BPL L99BB
    BMI L99B2
L99C5:
    STX $C209
    LDA $C228,X
    JSR L99F0
    BEQ L99DD
    JSR L9ABC
    LDX $C209
    LDA #$00
    STA $C22C,X
    BEQ L99AC
L99DD:
    JSR L9C2D
    LDA #$00
    STA $8038
    SEC
L99E6:
    PLA
L99E7:
    STA $19
    PLA
    TAY
    PLA
    TAX
    LDA $19
    RTS
L99F0:
    STA $19
    LDX $C20F
    LDY #$03
L99F7:
    CPX $19
    BEQ L9A05
    INX
    CPX #$60
    BNE L9A02
    LDX #$20
L9A02:
    DEY
    BPL L99F7
L9A05:
    RTS
L9A06:
    LDA $A1
    CMP $8048
    BCC L9A16                           ; workspace
    JSR L9922
    LDA #$00
    STA $A2
    STA $A1
L9A16:
    RTS
L9A17:
    JSR L9A06
    LDX $C209
    LDA $C22C,X
    BMI L9A25                           ; workspace
    JMP L9AAC
L9A25:
    AND #$40
    BEQ L9A2C
    JMP L9A73
L9A2C:
    JSR L9ABC
    LDX $C209
    LDY $C228,X
    LDX #$03
L9A37:
    LDA $C22C,X
    AND #$40                            ; workspace
    BEQ L9A44
    TYA
    CMP $C228,X
    BEQ L9A5E
L9A44:
    DEX
    BPL L9A37
    LDX #$03
    STY $C215
    LDY $C20F
L9A4F:
    CPY $C215                           ; workspace
    BEQ L9A6B
    INY
    CPY #$60
    BNE L9A5B
    LDY #$20
L9A5B:
    DEX
    BPL L9A4F                           ; workspace
L9A5E:
    LDX $C209
    LDA #$00
    STA $C228,X
    STA $C22C,X
    BEQ L9AAC
L9A6B:
    LDX $C209
    LDA #$C0
    STA $C22C,X
L9A73:
    LDA $C228,X
    CMP $C20F                           ; workspace
    BNE L9AAC
    LDY $C20F
    INY
    CPY #$60
    BNE L9A85
    LDY #$20
L9A85:
    STY $C20F                           ; workspace
    LDA $9B03,X
    STA $21
    LDA $9B07,X
    STA $22
    LDA #$03
    STA $C20B
    LDY #$00
    LDA ($21),Y                         ; workspace
    SEC
    SBC #$02
    STA $C217
    INY
    LDA ($21),Y
    STA $8034
    ASL                                 ; workspace
    STA $C216
    RTS
L9AAC:
    LDX $C209
    INX
    CPX #$04                            ; workspace
    BNE L9AB6
    LDX #$00
L9AB6:
    STX $C209
    JMP L9A17
L9ABC:
    LDA $C228,X                         ; workspace
    STA $C206
    LDX #$19
    LDY #$20                            ; workspace
    JSR L9BA4
    LDA #$40
    STA $C21D
    LDA #$E6
    STA $C21E                           ; workspace
    LDA $C206                           ; workspace
    JSR L9B10                           ; workspace
    JSR L9B0B
    LDA $C21D
    STA $C207
    LDA $C21E
    STA $C208
    JSR L991E
    LDX #$00
    STX $C20C
L9AF0:
    LDA $C203,X
    JSR L9926
    INC $C20C
    LDX $C20C
    CPX #$06
    BNE L9AF0
    JMP L9922
    .byte $34, $C8, $5C, $F0, $C2, $C2, $C3, $C3  ; $9B03 4.\.....
L9B0B:
    LDA #$00
    JSR L9B10                           ; workspace
L9B10:
    PHA                                 ; workspace
    STA $C21F
    TXA
    PHA                                 ; workspace
    LDX #$07
L9B18:
    CLC
    ROL $C21F
    ROL $C21E
    ROL $C21D
    BCC L9B34                           ; workspace
    LDA $C21D
    EOR #$10
    STA $C21D

; ============================================================
; PROTO_FLOW_CONTROL
; ============================================================
    LDA $C21E                           ; PROTO_DISCONNECT
    EOR #$21
    STA $C21E
L9B34:
    DEX
    BPL L9B18
    PLA
    TAX
    PLA
    RTS

; --- PROTO_FLOW_CONTROL ---
; Wait for response packet, check token
PROTO_FLOW_CONTROL:
    JSR PROTO_DISCONNECT
    JSR L9A17
    LDA $8034
    CMP #$41
    BEQ L9B52
    CMP #$42
    BEQ L9B52
    CMP #$40
    BEQ L9B52
L9B50:
    CLC
    RTS
L9B52:
    JSR MODEM_REG_READ_STATUS
    LDA #$00
    STA $C100,Y
    LDA $8034                           ; PRINT_STATUS_MSG
    CMP #$40                            ; CLEAR_STATUS
    BEQ L9B50
    CMP #$42
    BEQ L9B74
    LDX #$00
    LDY #$C1                            ; MODEM_SEND_CMD
    JSR PRINT_STATUS_MSG
    JSR CLEAR_STATUS
    JSR PROTOCOL_STATE_INIT
    SEC
    RTS
L9B74:
    LDX #$01                            ; MODEM_REG_READ
    JMP MODEM_SEND_CMD

; --- PROTO_SEND_PACKET ---
; Send complete packet with framing ($01...$02)
PROTO_SEND_PACKET:
    JSR L9C36
    LDX #$03
    LDA #$20
    JSR MODEM_REG_WRITE                 ; workspace
L9B83:
    JSR MODEM_REG_READ                  ; workspace
    AND #$20                            ; workspace
    BNE L9B83

; --- PROTO_RECV_PACKET ---
; Initialize protocol receive state
PROTO_RECV_PACKET:
    LDA #$20
    STA $C20E
    STA $C20F
    STA $C204
    STA $C205
    LDA #$06
    STA $C203                           ; workspace
    STA $C220
    STA $8038
    RTS
L9BA4:
    BIT $8011
    BPL L9C0A
    STA $C226
    TYA
    AND #$3F
    CMP #$20
    BCC L9BC5
    AND #$1F
    STA $C225
    ASL
    ADC $C225
    ADC #$0B
    LDY #$9C
    BCC L9BD3
    INY
    BNE L9BD3
L9BC5:
    STA $C225
    ASL
    ADC $C225
    ADC #$14
    LDY #$9C
    BCC L9BD3
    INY
L9BD3:
    STA $1B
    STY $1C
    LDY #$00
L9BD9:
    LDA ($1B),Y
    CMP #$20
    BEQ L9BE1
    AND #$1F
L9BE1:
    ORA #$80
    STA $07C0,X
    INX
    INY
    CPY #$03
    BNE L9BD9
    INX
    LDA $C226
    LSR
    LSR
    LSR
    LSR
    JSR L9BFD
    INX
    LDA $C226
    AND #$0F
L9BFD:
    ORA #$B0
    CMP #$BA
    BCC L9C07
    ADC #$06
    AND #$8F
L9C07:
    STA $07C0,X
L9C0A:
    RTS
    .byte $41, $43, $4B, $44, $49, $52, $44, $41, $54, $4F, $4B, $20, $45, $52, $52, $46  ; $9C0B ACKDIRDATOK ERRF
    .byte $54, $4C, $43, $4F, $4D  ; $9C1B TLCOM
L9C20:
    LDY #$40
    LDA $02A6
    BNE L9C29
    LDY #$42
L9C29:
    STY CIA1_TAHI
    RTS
L9C2D:
    JSR L9C20
    LDA #$46
    LDY #$9C
    BNE L9C3D
L9C36:
    JSR L9C20
    LDA #$31
    LDY #$EA
L9C3D:
    SEI
    STA IRQ_VECTOR
    STY $0315
    CLI
    RTS
    JSR L9C7D
    LDX #$00
    JSR MODEM_REG_READ
    AND #$20
    BEQ L9C55
    JMP $EA31
L9C55:
    LDX #$02
    JMP MODEM_SEND_CMD                  ; workspace
    JSR L9C7D
    JSR L9C8F
    JMP L9C71
    JSR L9D00
    INC $C221
    BNE L9C6E
    INC $C222
L9C6E:
    JSR L9C7D                           ; CIA1_PRB
L9C71:
    JSR KERNAL_UDTIM                    ; CIA1_PRB
    LDA CIA1_ICR
    PLA
    TAY
    PLA
    TAX
    PLA
    RTI
L9C7D:
    LDA CIA1_PRB                        ; MODEM_SEND_CMD
    CMP CIA1_PRB
    BNE L9C7D                           ; workspace
    CMP #$7B
    BEQ L9C8A
    RTS
L9C8A:
    LDX #$00
    JMP MODEM_SEND_CMD
L9C8F:
    JSR L9D54
    BIT $C223
    BMI L9C98
    RTS
L9C98:
    LDY $C485
    LDA $C486
    CPY #$20
    BNE L9CA5
    LDA $C487
L9CA5:
    LDX #$20
    JSR L9BA4
    LDA $C485
    CMP #$20
    BEQ L9CF1
    LDX #$03
L9CB3:
    LDA $C22C,X
    BPL L9CBD
    DEX
    BPL L9CB3
    BMI L9CF1
L9CBD:
    LDA $1B
    PHA
    LDA $1C
    PHA
    LDA $9B03,X
    STA $1B
    LDA $9B07,X
    STA $1C
    LDA #$80
    STA $C22C,X
    LDA $C485
    STA $C230,X
    LDA $C486
    STA $C228,X
    LDY #$00
L9CE0:
    LDA $C484,Y
    STA ($1B),Y
    INY
    CPY $C212
    BNE L9CE0
    PLA
    STA $1C
    PLA
    STA $1B
L9CF1:
    JMP L9E3C
    .byte $93, $0E, $C1, $42, $4F, $52, $54, $45, $44, $0D, $0D, $00  ; $9CF4 ...BORTED...
L9D00:
    JSR L9D54
    BIT $C223
    BMI L9D09                           ; workspace
    RTS
L9D09:
    LDA $C485
    CMP #$20
    BNE L9D40
    LDY #$03                            ; workspace
L9D12:
    LDA $C484,Y
    STY $C227
    LDX #$20
    LDY #$20
    JSR L9BA4
    LDY $C227
    LDA $C484,Y
    LDX $8043
L9D28:
    CMP $C228,X
    BEQ L9D32
    DEX
    BPL L9D28
    BMI L9D37
L9D32:
    LDA #$00
    STA $C22C,X
L9D37:
    INY
    CPY $C212
    BNE L9D12
L9D3D:
    JMP L9E3C
L9D40:
    LDA $C486
    JSR L99F0
    BNE L9D3D
    LDX $8043
    LDA #$00
L9D4D:
    STA $C22C,X
    DEX
    BPL L9D4D
    RTS
L9D54:
    LDA #$00
    STA $C223
    LDX #$00
    JSR MODEM_REG_READ                  ; MODEM_SEND_CMD
    TAX                                 ; workspace
    AND #$40
    BNE L9D85
    TXA                                 ; workspace
    AND #$20
    BNE L9D6D
    LDX #$02
    JMP MODEM_SEND_CMD
L9D6D:
    INC $C218
    BNE L9D7F
    INC $C219
    LDA $8049
    BEQ L9D7F
    CMP $C219                           ; workspace
    BEQ L9D80                           ; workspace
L9D7F:
    RTS
L9D80:
    LDX #$03
    JMP MODEM_SEND_CMD                  ; MODEM_REG_READ
L9D85:
    LDA #$00                            ; workspace
    STA $A2
    STA $C218
    STA $C219
    LDX #$04
    JSR MODEM_REG_READ
    BIT $C213
    BPL L9DA3
    CMP #$01
    BNE L9DA2
    LDA #$00
    STA $C213
L9DA2:
    RTS
L9DA3:
    CMP #$01
    BNE L9DAF
    LDA #$93                            ; workspace
    JSR L9E50
    JMP L9E41
L9DAF:
    CMP #$02
    BNE L9DE9
    LDA $C484
    CMP $C212
    BEQ L9DBF                           ; workspace
    LDA #$8E
    BNE L9E39
L9DBF:
    LDA $C21A
    BEQ L9DC8
L9DC4:
    LDA #$83
    BNE L9E39
L9DC8:
    LDA $C21B
    BNE L9DC4
    LDA $C212
    CMP #$05
    BCS L9DD8
    LDA #$95
    BNE L9E39                           ; workspace
L9DD8:
    DEC $C212
    DEC $C212
    LDA #$A0
    JSR L9E50
    LDA #$FF
    STA $C223                           ; workspace
    RTS
L9DE9:
    LDY $C212
    CPY #$94                            ; workspace
    BNE L9DF4
    LDA #$8F
    BNE L9E39
L9DF4:
    BIT $C214
    BPL L9E04
    LDX #$00
    STX $C214                           ; workspace
    SEC
    SBC #$20
    JMP L9E0E
L9E04:
    CMP #$03
    BNE L9E0E
    LDA #$FF
    STA $C214
    RTS
L9E0E:
    STA $C484,Y                         ; workspace
    INC $C212                           ; workspace
    STA $C21C
    LDX #$07
L9E19:
    CLC
    ROL $C21C
    ROL $C21B
    ROL $C21A
    BCC L9E35                           ; workspace
    LDA $C21A
    EOR #$10
    STA $C21A
    LDA $C21B
    EOR #$21
    STA $C21B
L9E35:
    DEX
    BPL L9E19
    RTS
L9E39:
    JSR L9E50
L9E3C:
    LDA #$FF
    STA $C213
L9E41:
    LDA #$00
    STA $C212
    STA $C214
    STA $C21A
    STA $C21B
    RTS
L9E50:
    BIT $8011
    BPL L9E58
    STA $07E7
L9E58:
    RTS
    .byte $C3, $4F, $4E, $4E, $45, $43, $54, $49, $4E, $47, $2E, $2E, $2E, $0D, $11, $00  ; $9E59 .ONNECTING......

; --- PROTO_CONNECT ---
; Connection handshake — wait for *CON from server
PROTO_CONNECT:
    LDX #$00
    JSR MODEM_REG_READ
    AND #$20                            ; MODEM_SEND_CMD
    BNE L9E89
    LDX #$08
    JSR MODEM_REG_READ
    AND #$40
    BNE L9E80
    LDX #$02
    JMP MODEM_SEND_CMD                  ; VIC_BORDER
L9E80:
    JSR KERNAL_GETIN
    CMP #$03
    BNE PROTO_CONNECT
    BEQ L9EE1
L9E89:
    LDA $8012
    STA VIC_BORDER
    LDX #$03
    LDA #$D0
    JSR MODEM_REG_WRITE
    JSR L906E
    JSR L906E
    BIT $8010
    BVC L9EA6
    JSR L96D8
    CLC
    RTS
L9EA6:
    LDX #$59
    LDY #$9E
    JSR PRINT_STRING                    ; workspace
    LDA #$00
    STA $C200
    STA $C202
    STA $1F
    STA $20
    STA $C201
    LDA #$C8
    LDY #$9F
    JSR L9C3D
    LDA $8046
    STA CIA1_TAHI
    JSR L9FA9
    JSR L9FA9
    LDA #$40
    LDX #$08
    JSR MODEM_REG_WRITE
L9ED6:
    LDX $20
    CPX #$0A
    BCS L9EE3
    JSR L9F90
    BNE L9ED6
L9EE1:
    SEC                                 ; MODEM_REG_READ
    RTS
L9EE3:
    JSR L9F90
    BEQ L9EE1
    LDX $1F
    CPX $20
    BNE L9F14
    LDX #$00
    JSR MODEM_REG_READ
    TAX
    BPL L9EE3
    LDX $C202
    BMI L9EE3
    JSR L9FBC
    LDA $8052,X
    INX
    CPX $8051
    BNE L9F09
    LDX #$FF
L9F09:
    STX $C202
    LDX #$04
    JSR MODEM_REG_WRITE
    JMP L9EE3
L9F14:
    LDA $C234,X
    INC $1F
    AND #$7F
    CMP #$20
    BCC L9F3B
    CMP #$41
    BCC L9F3B
    CMP #$5B
    BCS L9F2B
    ORA #$80
    BNE L9F3B
L9F2B:
    CMP #$60
    BCC L9F3B
    BEQ L9F39
    CMP #$7B
    BCS L9F39
    AND #$DF
    BNE L9F3B
L9F39:
    LDA #$00
L9F3B:
    CMP #$0D
    BEQ L9F43
    CMP #$20
    BCC L9EE3
L9F43:
    LDX $C201                           ; workspace
    BNE L9F4C
    CMP #$3F
    BEQ L9F55
L9F4C:
    CMP #$2A
    BNE L9F59
    LDX #$00
    STX $C201
L9F55:
    SEC
    ROR $C200
L9F59:
    BIT $8010
    BMI L9F63
    BIT $C200
    BPL L9F66
L9F63:
    JSR KERNAL_CHROUT
L9F66:
    AND #$7F
    STA $0200,X
    CPX #$4F
    BEQ L9F72
    INC $C201                           ; workspace
L9F72:
    CMP #$0D
    BEQ L9F79
L9F76:
    JMP L9EE3
L9F79:
    LDA #$00
    STA $C200
    STA $C201
    LDX #$03
L9F83:
    LDA $0200,X
    CMP $804D,X
    BNE L9F76
    DEX
    BPL L9F83
    CLC
    RTS
L9F90:
    BIT $8010
    BPL L9FA3
    LDX #$08
    JSR MODEM_REG_READ
    AND #$40
    BNE L9FA3
    LDX #$02                            ; MODEM_REG_WRITE
    JMP MODEM_SEND_CMD
L9FA3:
    JSR KERNAL_GETIN
    CMP #$03
    RTS
L9FA9:
    LDX #$08
    LDA #$10
    JSR MODEM_REG_WRITE
L9FB0:
    JSR MODEM_REG_READ
    AND #$10
    BNE L9FB0
    LDA #$0D
    JMP MODEM_WAIT_READY
L9FBC:
    LDA #$00
    STA $A2
    LDA $8044
L9FC3:
    CMP $A2
    BCS L9FC3                           ; MODEM_REG_READ
    RTS
    LDX #$00
    JSR MODEM_REG_READ
    TAY
    AND #$40
    BEQ L9FE1
    LDX #$04
    JSR MODEM_REG_READ
    LDX $20
    STA $C234,X                         ; MODEM_SEND_CMD
    INC $20
L9FDE:
    JMP $EA31
L9FE1:
    TYA
    AND #$20
    BNE L9FDE
    LDX #$02
    JMP MODEM_SEND_CMD
    .byte $00, $00, $00, $00, $00, $00, $AA, $AA, $AA, $AA, $AA, $AA, $AA, $AA, $AA, $AA  ; $9FEB ................
    .byte $AA, $AA, $AA, $AA, $AA  ; $9FFB .....
